<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Fit complex nonlinear mixed-effects population PK/PD models with Stochastic Approximation Expectation-Maximization in ferx.">

<title>SAEM estimation for population PK/PD – ferx-core</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/ferx-favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1a6b8152d35ce99ad89fbf7beccf1728.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-a739b0675e4828d39130ef8f9cb3f71b.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1a6b8152d35ce99ad89fbf7beccf1728.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-112e5622ee747e1c4dc4e363d1626892.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-570b18dfac9eba3e29c33095147666fc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-112e5622ee747e1c4dc4e363d1626892.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="SAEM estimation for population PK/PD">
<meta property="og:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD and pharmacometrics">
<meta property="og:site_name" content="ferx-core">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="SAEM estimation for population PK/PD">
<meta name="twitter:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD and pharmacometrics">
<meta name="twitter:card" content="summary">
<link rel="canonical" href="https://ferx-nlme.org/ferx-core/estimation/saem.html">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://ferx-nlme.org/" class="navbar-brand navbar-brand-logo">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo light-content">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="https://ferx-nlme.org/">
    <span class="navbar-title">ferx-core</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/get-started.html"> 
<span class="menu-text">Get started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/design.html"> 
<span class="menu-text">Design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/features.html"> 
<span class="menu-text">Features</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/changelog.html"> 
<span class="menu-text">Changelog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/roadmap.html"> 
<span class="menu-text">Roadmap</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/blog/"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/ferx-core/"> 
<span class="menu-text">ferx-core</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/ferx-book/"> 
<span class="menu-text">ferx-r</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/reference/"> 
<span class="menu-text">Reference</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/FeRx-NLME"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../estimation/index.html">Estimation Methods</a></li><li class="breadcrumb-item"><a href="../estimation/saem.html">SAEM</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../maturity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feature Maturity</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../quick-start.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quick Start</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../model-file/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model File Reference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/iov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-Occasion Variability (IOV)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/individual-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Individual Parameters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariate-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/structural-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/lagtime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lagtime</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/steady-state.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Steady-State Doses (SS=1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/error-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Error Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/bloq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LOQ-Censored Observations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/ode-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/absorption.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Built-in Absorption Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/initial-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Initial Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/diffusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stochastic Differential Equations (SDE / Diffusion)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariate-nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>[covariate_nn]</code> — Deep Compartment Models (DCM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/data-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/derived.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Derived Columns (<code>[derived]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Output Columns (<code>[output]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/fit-options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fit Options</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/adaptive-dosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adaptive (Feedback) Dosing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/event-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-to-Event Endpoints (<code>[event_model]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical endpoints — <code>[binary_model]</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/markov-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Markov models ([markov_model])</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../estimation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimation Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/foce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FOCE / FOCEI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/agq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AGQ — Adaptive Gaussian Quadrature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/gauss-newton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gauss-Newton (BHHH)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/saem.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">SAEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/sir.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling Importance Resampling (SIR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/importance-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importance Sampling (IMP)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/frem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FREM (Full Random Effects Model)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/impmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IMPMAP — Importance Sampling assisted by Mode A Posteriori</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayesian estimation (MCMC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/vi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variational Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/parameterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Packed Parameter Space</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/optimizers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outer Optimizers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/tte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-to-Event (TTE) Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical endpoints (binary / logistic)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/ctmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous-time Markov models (CTMM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixture Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameter Priors (penalized ML / MAP)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tools/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tools</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/gam-screening.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GAM covariate screening</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Search configuration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/covsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/modelsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural model search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/ruvsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Residual-error search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/iivsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variability-structure search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/iovsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-occasion variability search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/amd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Automatic model development</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/global-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Global model search</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data-format.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Format</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CLI Reference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Output Files</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../warnings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Warnings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../file-formats/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">File Formats</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../file-formats/fitrx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The <code>.fitrx</code> Fit Bundle</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../file-formats/check-report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Check Report (<code>ferx check --json</code>)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../examples/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Examples</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/one-cpt-oral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One-Compartment Oral (Warfarin)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/two-cpt-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-Compartment IV Bolus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/covariates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/ode-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Model (Michaelis-Menten)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/bloq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BLOQ (M3 method)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/iov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-Occasion Variability (IOV)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/iov-saem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IOV with SAEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/multiple-dosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Dosing (ADDL Column)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/steady-state.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Steady-State Dosing (SS Column)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit Scaling (<code>[scaling]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/derived-output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Derived Columns and Output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/data-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Selection (IGNORE / ACCEPT)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/ode-lagtime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Model with Absorption Lag Time</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/transit-absorption.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transit Absorption (Two-Compartment)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/sde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stochastic Differential Equations (SDE)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/frem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FREM (Covariate Analysis)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/multistart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-Start: Michaelis-Menten Elimination</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../api/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rust API</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Core Types</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/parsing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/model-editing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model editing</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../development/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Development</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/contributing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributing to FeRx development</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/sdlc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Development Lifecycle (SDLC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/docs-lint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Docs linter</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#saem" id="toc-saem" class="nav-link active" data-scroll-target="#saem">SAEM</a>
  <ul>
  <li><a href="#algorithm-overview" id="toc-algorithm-overview" class="nav-link" data-scroll-target="#algorithm-overview">Algorithm Overview</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  <li><a href="#two-phase-schedule" id="toc-two-phase-schedule" class="nav-link" data-scroll-target="#two-phase-schedule">Two-Phase Schedule</a>
  <ul class="collapse">
  <li><a href="#phase-1-exploration-iterations-1-to-k1" id="toc-phase-1-exploration-iterations-1-to-k1" class="nav-link" data-scroll-target="#phase-1-exploration-iterations-1-to-k1">Phase 1: Exploration (iterations 1 to K1)</a></li>
  <li><a href="#phase-2-convergence-iterations-k11-to-k1k2" id="toc-phase-2-convergence-iterations-k11-to-k1k2" class="nav-link" data-scroll-target="#phase-2-convergence-iterations-k11-to-k1k2">Phase 2: Convergence (iterations K1+1 to K1+K2)</a></li>
  </ul></li>
  <li><a href="#per-iteration-steps" id="toc-per-iteration-steps" class="nav-link" data-scroll-target="#per-iteration-steps">Per-Iteration Steps</a>
  <ul class="collapse">
  <li><a href="#e-step-sampling" id="toc-e-step-sampling" class="nav-link" data-scroll-target="#e-step-sampling">1. E-Step: Sampling</a>
  <ul class="collapse">
  <li><a href="#metropolis-hastings-default-n_leapfrog-0" id="toc-metropolis-hastings-default-n_leapfrog-0" class="nav-link" data-scroll-target="#metropolis-hastings-default-n_leapfrog-0">Metropolis-Hastings (default, <code>n_leapfrog = 0</code>)</a></li>
  <li><a href="#choosing-n_mh_steps" id="toc-choosing-n_mh_steps" class="nav-link" data-scroll-target="#choosing-n_mh_steps">Choosing <code>n_mh_steps</code></a></li>
  <li><a href="#hmc-hamiltonian-monte-carlo-n_leapfrog-0" id="toc-hmc-hamiltonian-monte-carlo-n_leapfrog-0" class="nav-link" data-scroll-target="#hmc-hamiltonian-monte-carlo-n_leapfrog-0">HMC (Hamiltonian Monte Carlo, <code>n_leapfrog &gt; 0</code>)</a></li>
  </ul></li>
  <li><a href="#stochastic-approximation-update" id="toc-stochastic-approximation-update" class="nav-link" data-scroll-target="#stochastic-approximation-update">2. Stochastic Approximation Update</a></li>
  <li><a href="#m-step-for-omega-closed-form" id="toc-m-step-for-omega-closed-form" class="nav-link" data-scroll-target="#m-step-for-omega-closed-form">3. M-Step for Omega (Closed Form)</a></li>
  <li><a href="#4-m-step-for-theta-and-sigma-optimization" id="toc-4-m-step-for-theta-and-sigma-optimization" class="nav-link" data-scroll-target="#4-m-step-for-theta-and-sigma-optimization">4. M-Step for Theta and Sigma (Optimization)</a>
  <ul class="collapse">
  <li><a href="#saem-mstep-closed-form" id="toc-saem-mstep-closed-form" class="nav-link" data-scroll-target="#saem-mstep-closed-form">Closed-form EM update for mu-referenced thetas</a></li>
  <li><a href="#saem-mstep-covariate-mu-ref" id="toc-saem-mstep-covariate-mu-ref" class="nav-link" data-scroll-target="#saem-mstep-covariate-mu-ref">Covariate mu-references: typical values that read several thetas</a></li>
  <li><a href="#scalar-residual-error-update" id="toc-scalar-residual-error-update" class="nav-link" data-scroll-target="#scalar-residual-error-update">Scalar residual-error update</a></li>
  <li><a href="#saem-mstep-bobyqa" id="toc-saem-mstep-bobyqa" class="nav-link" data-scroll-target="#saem-mstep-bobyqa">The NLopt M-step (BOBYQA)</a></li>
  <li><a href="#saem-mstep-no-closed-form" id="toc-saem-mstep-no-closed-form" class="nav-link" data-scroll-target="#saem-mstep-no-closed-form">Thetas the closed-form update cannot reach</a></li>
  </ul></li>
  <li><a href="#saem-mstep-jensen" id="toc-saem-mstep-jensen" class="nav-link" data-scroll-target="#saem-mstep-jensen">Averaging a maximiser is not maximising the average</a>
  <ul class="collapse">
  <li><a href="#the-two-alternatives" id="toc-the-two-alternatives" class="nav-link" data-scroll-target="#the-two-alternatives">The two alternatives</a></li>
  <li><a href="#measured" id="toc-measured" class="nav-link" data-scroll-target="#measured">Measured</a></li>
  <li><a href="#why-score_sa-is-not-the-default" id="toc-why-score_sa-is-not-the-default" class="nav-link" data-scroll-target="#why-score_sa-is-not-the-default">Why <code>score_sa</code> is not the default</a></li>
  </ul></li>
  <li><a href="#what-saem-does-about-it-now" id="toc-what-saem-does-about-it-now" class="nav-link" data-scroll-target="#what-saem-does-about-it-now">The exploration cap (<code>mstep_damping</code>) is a hold, not a cure</a></li>
  <li><a href="#comparing-a-saem-fit-to-focei-read-the-importance-sampled-objective" id="toc-comparing-a-saem-fit-to-focei-read-the-importance-sampled-objective" class="nav-link" data-scroll-target="#comparing-a-saem-fit-to-focei-read-the-importance-sampled-objective">Comparing a SAEM fit to FOCEI: read the importance-sampled objective</a></li>
  <li><a href="#adaptive-step-sizes" id="toc-adaptive-step-sizes" class="nav-link" data-scroll-target="#adaptive-step-sizes">5. Adaptive Step Sizes</a>
  <ul class="collapse">
  <li><a href="#scale_adaptation-interval" id="toc-scale_adaptation-interval" class="nav-link" data-scroll-target="#scale_adaptation-interval"><code>scale_adaptation = interval</code></a></li>
  <li><a href="#scale_adaptation-robbins_monro-default" id="toc-scale_adaptation-robbins_monro-default" class="nav-link" data-scroll-target="#scale_adaptation-robbins_monro-default"><code>scale_adaptation = robbins_monro</code> (default)</a></li>
  <li><a href="#scale_deadband-only-correct-a-chain-that-is-off-target" id="toc-scale_deadband-only-correct-a-chain-that-is-off-target" class="nav-link" data-scroll-target="#scale_deadband-only-correct-a-chain-that-is-off-target"><code>scale_deadband</code> — only correct a chain that is off target</a></li>
  <li><a href="#acceptance-rate-diagnostics" id="toc-acceptance-rate-diagnostics" class="nav-link" data-scroll-target="#acceptance-rate-diagnostics">Acceptance-rate diagnostics</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#post-saem-finalization" id="toc-post-saem-finalization" class="nav-link" data-scroll-target="#post-saem-finalization">Post-SAEM Finalization</a></li>
  <li><a href="#conditional-distribution-conditional-mode-vs.-distribution" id="toc-conditional-distribution-conditional-mode-vs.-distribution" class="nav-link" data-scroll-target="#conditional-distribution-conditional-mode-vs.-distribution">Conditional Distribution (conditional mode vs.&nbsp;distribution)</a>
  <ul class="collapse">
  <li><a href="#validation-against-saemix-and-nonmem" id="toc-validation-against-saemix-and-nonmem" class="nav-link" data-scroll-target="#validation-against-saemix-and-nonmem">Validation against saemix and NONMEM</a></li>
  <li><a href="#validation-of-the-logit-closed-form-m-step-918" id="toc-validation-of-the-logit-closed-form-m-step-918" class="nav-link" data-scroll-target="#validation-of-the-logit-closed-form-m-step-918">Validation of the logit closed-form M-step (#918)</a></li>
  <li><a href="#validation-of-the-covariate-mu-reference-m-step-619" id="toc-validation-of-the-covariate-mu-reference-m-step-619" class="nav-link" data-scroll-target="#validation-of-the-covariate-mu-reference-m-step-619">Validation of the covariate mu-reference M-step (#619)</a></li>
  <li><a href="#validation-of-the-joint-m-step-for-a-shared-theta-1620" id="toc-validation-of-the-joint-m-step-for-a-shared-theta-1620" class="nav-link" data-scroll-target="#validation-of-the-joint-m-step-for-a-shared-theta-1620">Validation of the joint M-step for a shared theta (#1620)</a></li>
  </ul></li>
  <li><a href="#inter-occasion-variability-iov" id="toc-inter-occasion-variability-iov" class="nav-link" data-scroll-target="#inter-occasion-variability-iov">Inter-Occasion Variability (IOV)</a></li>
  <li><a href="#models-with-no-random-effects-are-rejected" id="toc-models-with-no-random-effects-are-rejected" class="nav-link" data-scroll-target="#models-with-no-random-effects-are-rejected">Models with no random effects are rejected</a></li>
  <li><a href="#configuration" id="toc-configuration" class="nav-link" data-scroll-target="#configuration">Configuration</a></li>
  <li><a href="#tuning-guide" id="toc-tuning-guide" class="nav-link" data-scroll-target="#tuning-guide">Tuning Guide</a>
  <ul class="collapse">
  <li><a href="#not-converging" id="toc-not-converging" class="nav-link" data-scroll-target="#not-converging">Not Converging</a></li>
  <li><a href="#pd-curve-thetas-collapse-on-cold-start-emax-sigmoid-readouts" id="toc-pd-curve-thetas-collapse-on-cold-start-emax-sigmoid-readouts" class="nav-link" data-scroll-target="#pd-curve-thetas-collapse-on-cold-start-emax-sigmoid-readouts">PD-curve thetas collapse on cold start (Emax / sigmoid readouts)</a></li>
  <li><a href="#ω-collapses-residual-error-inflates" id="toc-ω-collapses-residual-error-inflates" class="nav-link" data-scroll-target="#ω-collapses-residual-error-inflates">Ω Collapses / Residual Error Inflates</a></li>
  <li><a href="#block-ω-correlations-near-1-rank-1-collapse" id="toc-block-ω-correlations-near-1-rank-1-collapse" class="nav-link" data-scroll-target="#block-ω-correlations-near-1-rank-1-collapse">Block Ω correlations near ±1 (rank-1 collapse)</a></li>
  <li><a href="#the-additive-term-of-a-combined-error-model" id="toc-the-additive-term-of-a-combined-error-model" class="nav-link" data-scroll-target="#the-additive-term-of-a-combined-error-model">The additive term of a <code>combined()</code> error model</a></li>
  <li><a href="#iiv-on-residual-error-iiv_on_ruv-σ-ω_ruv-ridge" id="toc-iiv-on-residual-error-iiv_on_ruv-σ-ω_ruv-ridge" class="nav-link" data-scroll-target="#iiv-on-residual-error-iiv_on_ruv-σ-ω_ruv-ridge">IIV on residual error (<code>iiv_on_ruv</code>): σ × ω_RUV ridge</a></li>
  <li><a href="#slow-convergence" id="toc-slow-convergence" class="nav-link" data-scroll-target="#slow-convergence">Slow Convergence</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  </ul></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output">Output</a>
  <ul class="collapse">
  <li><a href="#why-γ-gamma-is-shown" id="toc-why-γ-gamma-is-shown" class="nav-link" data-scroll-target="#why-γ-gamma-is-shown">Why <code>γ</code> (gamma) is shown</a></li>
  <li><a href="#why-condnll-and-not-ofv" id="toc-why-condnll-and-not-ofv" class="nav-link" data-scroll-target="#why-condnll-and-not-ofv">Why <code>condNLL</code> and not <code>OFV</code></a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/FeRx-NLME/ferx-core/edit/main/estimation/saem.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-core/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../estimation/index.html">Estimation Methods</a></li><li class="breadcrumb-item"><a href="../estimation/saem.html">SAEM</a></li></ol></nav></header>





<section id="saem" class="level1">
<h1>SAEM</h1>
<blockquote class="blockquote">
<p><strong>Maturity: beta</strong> — see <a href="../maturity.html">Feature Maturity</a> for what this means.</p>
</blockquote>
<p>Stochastic Approximation Expectation-Maximization (SAEM) is an alternative estimation method that uses MCMC sampling for random effects instead of MAP optimization. It is more robust to local minima and can handle complex random effect structures, including models with <strong>inter-occasion variability (IOV)</strong>.</p>
<section id="algorithm-overview" class="level2">
<h2 class="anchored" data-anchor-id="algorithm-overview">Algorithm Overview</h2>
<p>SAEM replaces the deterministic inner loop of FOCE with stochastic sampling, following the Monolix convention with a two-phase step-size schedule.</p>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<ul>
<li>Delyon, Lavielle, Moulines (1999). <em>Convergence of a stochastic approximation version of the EM algorithm.</em> Annals of Statistics, 94–128.</li>
<li>Kuhn &amp; Lavielle (2004). <em>Coupling a stochastic approximation version of EM with an MCMC procedure.</em> ESAIM: Probability and Statistics 8:115–131.</li>
</ul>
</section>
</section>
<section id="two-phase-schedule" class="level2">
<h2 class="anchored" data-anchor-id="two-phase-schedule">Two-Phase Schedule</h2>
<section id="phase-1-exploration-iterations-1-to-k1" class="level3">
<h3 class="anchored" data-anchor-id="phase-1-exploration-iterations-1-to-k1">Phase 1: Exploration (iterations 1 to K1)</h3>
<p>Step size <span class="math inline">\(\gamma_k = 1\)</span>. The algorithm explores the parameter space rapidly, with the sufficient statistics being fully replaced each iteration. This allows fast movement toward the basin of the MLE.</p>
<p>Default: 150 iterations.</p>
</section>
<section id="phase-2-convergence-iterations-k11-to-k1k2" class="level3">
<h3 class="anchored" data-anchor-id="phase-2-convergence-iterations-k11-to-k1k2">Phase 2: Convergence (iterations K1+1 to K1+K2)</h3>
<p>Step size <span class="math inline">\(\gamma_k = 1/(k - K_1)\)</span>. The algorithm performs a decreasing-weight average, which guarantees almost-sure convergence to the MLE under regularity conditions.</p>
<p>Default: 250 iterations.</p>
</section>
</section>
<section id="per-iteration-steps" class="level2">
<h2 class="anchored" data-anchor-id="per-iteration-steps">Per-Iteration Steps</h2>
<p>Each SAEM iteration consists of:</p>
<section id="e-step-sampling" class="level3">
<h3 class="anchored" data-anchor-id="e-step-sampling">1. E-Step: Sampling</h3>
<p>For each subject, sample from the conditional distribution of random effects:</p>
<p><span class="math display">\[
p(\eta_i | y_i, \theta, \Omega, \sigma)
\]</span></p>
<p>Two samplers are available:</p>
<section id="metropolis-hastings-default-n_leapfrog-0" class="level4">
<h4 class="anchored" data-anchor-id="metropolis-hastings-default-n_leapfrog-0">Metropolis-Hastings (default, <code>n_leapfrog = 0</code>)</h4>
<p>Two MH kernels run per subject per SAEM iteration (the mixture of Kuhn &amp; Lavielle 2004):</p>
<p><strong>Kernel 1 — block proposal</strong>: run <code>n_mh_steps</code> symmetric random-walk steps <span class="math inline">\(\eta_{\text{prop}} = \eta_{\text{current}} + \delta_i \cdot L \cdot z\)</span>, with <span class="math inline">\(z \sim N(0, I)\)</span> and <span class="math inline">\(L = \text{chol}(\Omega)\)</span>. This mixes the joint scale efficiently. For <strong>FREM</strong> models the covariate ETAs are near-deterministic (their pseudo-observations pin them to a posterior SD of <span class="math inline">\(\approx\sqrt{\text{EPSCOV}} \ll \sqrt{\Omega_{jj}}\)</span>), so a full-scale joint proposal for them is rejected every time and the <em>joint</em> acceptance collapses to 0%. Each covariate coordinate is therefore damped in the block move by a factor <span class="math inline">\(\min(1, \sqrt{\text{EPSCOV}}/\sqrt{\Omega_{jj}})\)</span>, so the joint step still explores the correlated PK block while the componentwise sweep handles the covariate coordinates themselves. Ordinary (non-FREM) ETAs use a damping factor of exactly 1, i.e.&nbsp;the plain <span class="math inline">\(\text{chol}(\Omega)\,z\)</span> move (issue #895).</p>
<p><strong>Kernel 2 — componentwise sweep</strong>: for multi-η models, follow the block move with <span class="math inline">\(\max(2, \lfloor \texttt{n\_mh\_steps} / n_\eta \rfloor)\)</span> sweeps that perturb one coordinate at a time, <span class="math inline">\(\eta_j' = \eta_j + \delta_i^{\text{cw}} \cdot \sqrt{\Omega_{jj}} \cdot z\)</span>, holding the others fixed. Because the block proposal is shaped by <span class="math inline">\(\text{chol}(\Omega)\)</span>, once <span class="math inline">\(\Omega\)</span> drifts toward a high correlation the block move can only travel along that near-degenerate direction; the single-draw Ω M-step then feeds the correlation back into <span class="math inline">\(\Omega\)</span>, and during the <span class="math inline">\(\gamma=1\)</span> exploration phase this compounds into a runaway collapse toward a <strong>near rank-1 <span class="math inline">\(\Omega\)</span></strong> (every off-diagonal correlation <span class="math inline">\(\to \pm 1\)</span>, one variance <span class="math inline">\(\to 0\)</span>). A componentwise move can always shift a single η independently of <span class="math inline">\(\Omega\)</span>’s off-diagonals, so the sampled draws are not forced collinear. The kernel is skipped for single-η models (no off-diagonal to decorrelate).</p>
<p>Both kernels are symmetric in <span class="math inline">\(\eta\)</span>, so the proposal density cancels and the acceptance log-ratio is the difference of <code>individual_nll</code> values, which encodes the prior <span class="math inline">\(N(0, \Omega)\)</span> plus the observation likelihood.</p>
<p><strong>Acceptance</strong>: <span class="math inline">\(\min(1, \exp(\text{NLL}_{\text{current}} - \text{NLL}_{\text{prop}}))\)</span>. Target acceptance rate: 40%.</p>
<p><strong>Reported acceptance is combined.</strong> The <code>mh_accept_rate</code> column in the optimizer trace (and the verbose banner) is the <strong>combined block + componentwise</strong> rate. Reporting the block kernel alone is misleading for FREM-scale <span class="math inline">\(\Omega\)</span>: as above, the block move reads 0% acceptance even when the componentwise sweep is mixing the chain perfectly well. If the <em>combined</em> post-burn-in rate stays below 1%, the E-step genuinely is not mixing and SAEM appends a warning to <code>FitResult.warnings</code> — the sampled ETAs never moved, so the <span class="math inline">\(\Omega/\sigma\)</span> estimates are unreliable (issue #895).</p>
</section>
<section id="choosing-n_mh_steps" class="level4">
<h4 class="anchored" data-anchor-id="choosing-n_mh_steps">Choosing <code>n_mh_steps</code></h4>
<p><code>n_mh_steps</code> defaults to <code>auto</code>: the block count is sized from the dataset as</p>
<p><span class="math display">\[
\texttt{n\_mh\_steps} = \mathrm{clamp}\!\left(\left[\,2.5 \cdot \frac{n_{\text{obs}}}{n_{\text{subjects}} \cdot n_\eta}\,\right],\; 6,\; 20\right)
\]</span></p>
<p>i.e.&nbsp;from the observations each random effect has to be informed by. The resolved count and where it came from are printed under <code>verbose = true</code>, and an explicit <code>n_mh_steps = &lt;n&gt;</code> overrides the rule entirely.</p>
<p>Two scope notes. With <code>n_leapfrog &gt; 0</code> the count is <strong>not</strong> ignored: HMC replaces the block kernel for the subjects it can serve, but <code>n_mh_steps</code> still governs the MH-fallback subjects <em>and</em> still sizes the componentwise sweep, which runs after an HMC proposal as well. And <code>method = bayes</code> reads the option but not the rule — under <code>auto</code> its η block keeps the historical fixed 20, because the rule is calibrated on SAEM quantities and, per the kernel split below, what makes a low count safe on dense data is SAEM’s componentwise sweep, which that sampler does not run. An explicit count applies to both.</p>
<p>The reason it is not a constant is the step-scale controller. On a sparse population it reaches its 40 % acceptance target at <em>any</em> proposal count — measured at 0.39–0.46 on cefepime, vancomycin, busulfan and pembrolizumab for every count from 2 to 20 — so each proposal is worth the same fraction of a move, mixing per iteration is linear in the count, and so is the cost. Twenty proposals then buy nothing that six do not. The one benchmark where extra proposals pay for themselves is the one where the controller <em>cannot</em> reach its target: the Emax PKPD model below realises <strong>0.246</strong>, because its conditional <span class="math inline">\(p(\eta_i \mid y_i)\)</span> is far narrower than the <span class="math inline">\(N(0,\Omega)\)</span> prior the proposal is scaled by. Observations per subject per η is the cheapest proxy for that narrowing, which is why the rule reads it.</p>
<p>On that dense model it is specifically <strong>kernel 2</strong> that earns the count, not kernel 1. Breaking the coupling experimentally (6 block proposals with the 10 componentwise sweeps that 20 implies, against 20 block proposals with the 3 sweeps that 6 implies, 6 seeds each) puts the <em>sweeps</em> arm on 20’s numbers — <code>d_final</code> 0.043 and cross-seed stability 0.045, against 20’s own 0.029 / 0.044 — and the <em>block</em> arm on 6’s — 0.102 / 0.138 against 0.091 / 0.132. Raising <code>n_mh_steps</code> is how a model asks for more sweeps today, and at equal quality the two spellings cost the same wall here (28.4 s vs 29.0 s), so the rule sizes the block count and lets the sweep count follow (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1466">#1466</a> tracks separating them).</p>
<p>Measured on ferx <code>e7343462</code>, 6 seeds, 150 + 250 iterations, IS −2 log L from the <code>imp</code> readout and <code>d_final</code> against a 300/700/40 long run of the same build:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>dataset</th>
<th>obs/η</th>
<th><code>auto</code></th>
<th>IS −2 log L (auto vs 20)</th>
<th><code>d_final</code> (auto vs 20)</th>
<th>SAEM-stage CPU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>cefepime (458 subj, 3 η)</td>
<td>0.51</td>
<td>6</td>
<td>4296.3 vs 4294.9 (seed sd 1–2)</td>
<td>0.078 vs 0.075</td>
<td>−35 %</td>
</tr>
<tr class="even">
<td>vancomycin (100 subj, 3 η)</td>
<td>0.91</td>
<td>6</td>
<td>1135.3 vs 1135.0 (sd 0.4–0.9)</td>
<td>0.037 vs 0.033</td>
<td>−41 %</td>
</tr>
<tr class="odd">
<td>pembrolizumab (303 subj, 4 η)</td>
<td>1.02</td>
<td>6</td>
<td>5983.8 vs 5981.2 (sd 4–10)</td>
<td>0.179 vs 0.115</td>
<td>−29 %</td>
</tr>
<tr class="even">
<td>busulfan (600 subj, 3 η)</td>
<td>2.92</td>
<td>7</td>
<td>60044 vs 60045 (sd 3)</td>
<td>0.040 vs 0.041</td>
<td>−38…−40 %</td>
</tr>
<tr class="odd">
<td>Emax PKPD (100 subj, 2 η)</td>
<td>8.0</td>
<td>20</td>
<td>unchanged — the rule returns the old default</td>
<td></td>
<td>0 %</td>
</tr>
</tbody>
</table>
<p>CPU is the SAEM stage’s user+sys, 3 seeds on an uncontended lane at <code>--threads 2</code>. Busulfan’s 7 is quoted as a bracket because the count it resolves to sits between two measured cells (6 → 4.40 s and 8 → 4.23 s, against 7.10 s at 20) whose costs differ by less than the run-to-run spread.</p>
</section>
<section id="hmc-hamiltonian-monte-carlo-n_leapfrog-0" class="level4">
<h4 class="anchored" data-anchor-id="hmc-hamiltonian-monte-carlo-n_leapfrog-0">HMC (Hamiltonian Monte Carlo, <code>n_leapfrog &gt; 0</code>)</h4>
<p>When <code>n_leapfrog</code> is set to a positive integer (e.g.&nbsp;<code>3</code>), one HMC proposal replaces the <code>n_mh_steps</code> MH proposals per subject per iteration. HMC uses the gradient of the individual NLL to make longer, more directed moves through the posterior:</p>
<p><span class="math display">\[
H(\eta, p) = \text{NLL}(\eta) + \tfrac{1}{2} \|p\|^2
\]</span></p>
<p>with momentum <span class="math inline">\(p \sim N(0, I)\)</span> and a standard velocity Störmer-Verlet (leapfrog) integrator. Acceptance is on <span class="math inline">\(\Delta H\)</span>, targeting ~65% acceptance.</p>
<p><strong>Requirements</strong>: an analytical PK model (no ODE). The HMC gradient is the exact analytic <code>Dual2</code> η-gradient (the same one FOCEI uses). A warning is emitted if <code>n_leapfrog &gt; 0</code> but the model is out of the analytic provider’s scope.</p>
<p><strong>Per-subject fallback to MH</strong>: <code>hmc_step</code> silently falls back to MH for a subject when any of the following conditions hold: - The model uses an ODE (<code>[odes]</code> block present) - The model has no analytical PK path (no <code>tv_fn</code> — pure ODE-only models) - The Ω matrix has a non-finite log-determinant (degenerate variance) - The model is outside the analytic gradient’s scope (time-varying covariates, oral infusion, SS+reset, or LTBS). A η-dependent expression <code>obs_scale</code> is served analytically (since #486), so on a closed-form model it takes the HMC path — only LTBS combined with it falls back to MH.</p>
<p>In a single run with <code>n_leapfrog &gt; 0</code>, different subjects can therefore use different samplers. The acceptance rate reported in verbose output and the optimizer trace is an aggregate across all subjects; in mixed HMC/MH runs the target (65% for HMC, 40% for MH) may not be meaningful for the aggregate. The <code>n_mh_steps</code> option governs the number of proposals for MH-fallback subjects even when <code>n_leapfrog &gt; 0</code>.</p>
<p>The E-step sampling is parallelized across subjects using Rayon.</p>
<p>The startup banner reports the resolved E-step kernel on a <code>sampler:</code> line, e.g.&nbsp;<code>sampler:  Metropolis-Hastings random walk</code> or <code>sampler:  HMC (3 leapfrog steps, Dual2 analytic gradients)</code>. If <code>n_leapfrog &gt; 0</code> but HMC is unavailable (an ODE model, or one outside the analytic gradient’s scope), the line says so and reflects the MH fallback. Because SAEM is sampling-based rather than gradient-driven, it does not print the <code>gradient:</code> line that FOCE/FOCEI use — the <code>gradient_method</code> option only governs the inner EBE/Hessian step (used for diagnostics, and consumed by a following <code>imp</code> stage), not the SAEM iterations themselves.</p>
</section>
</section>
<section id="stochastic-approximation-update" class="level3">
<h3 class="anchored" data-anchor-id="stochastic-approximation-update">2. Stochastic Approximation Update</h3>
<p>Update the sufficient statistic for <span class="math inline">\(\Omega\)</span>:</p>
<p><span class="math display">\[
S_2 \leftarrow (1 - \gamma_k^\Omega) \cdot S_2 + \gamma_k^\Omega \cdot \frac{1}{N} \sum_{i=1}^{N} \eta_i \eta_i^T
\]</span></p>
<p><strong>Damped Ω step.</strong> The θ M-step uses the full <span class="math inline">\(\gamma_k\)</span> (1.0 during exploration), but the Ω sufficient statistic uses a <em>capped</em> step <span class="math inline">\(\gamma_k^\Omega = \min(\gamma_k, 0.1)\)</span>. With the full <span class="math inline">\(\gamma=1\)</span>, Ω would be overwritten every exploration iteration by a single warm-started, not-yet-equilibrated MCMC draw; for a correlated block that one snapshot is biased toward the chain’s current correlation, and the bias feeds back through <span class="math inline">\(\mathrm{chol}(\Omega)\)</span> into the next proposal — the same rank-1 runaway the componentwise kernel guards against, here attacked from the M-step side. Capping the Ω learning rate during exploration averages those draws (Robbins-Monro) and breaks the feedback while θ still moves at full speed. The cap applies during exploration only; in the convergence phase it is lifted and Ω uses the full decaying <span class="math inline">\(\gamma_k = 1/(k-K_1)\)</span> — the same Robbins-Monro schedule as θ — so the SA estimate settles correctly (by then the chain is equilibrated, so the single-draw overwrite risk no longer applies).</p>
<p><strong>Damped σ step.</strong> The residual σ that rides the numerical M-step gets its own capped step, <span class="math inline">\(\gamma_k^\sigma = \min(\gamma_k,\,0.2,\,\gamma_k^\theta)\)</span>, applied to <span class="math inline">\(\sigma^2\)</span> rather than to <span class="math inline">\(\log\sigma\)</span> (issue #1445). Until then it was the one SAEM statistic with no stochastic approximation at all — assigned outright in both phases — so the reported σ was a single draw of the M-step maximiser rather than its average. The cap is on in <strong>both</strong> phases, which is what distinguishes it from the Ω step: Ω accepts the <span class="math inline">\(\gamma=1\)</span> assignment at the first convergence iteration because <span class="math inline">\((1/N)\sum_i \eta_i\eta_i^T\)</span> over <span class="math inline">\(N\)</span> subjects is a well-determined statistic, while the σ maximiser of a <em>minority</em> variance component is not. The additive half of a <code>combined(PROP, ADD)</code> model on sparse data is exactly that: its single-draw conditional maximiser is boundary-heavy, so an assigned σ reports whichever value the last iteration happened to draw. Beyond <span class="math inline">\(k-K_1 = 5\)</span> the cap no longer binds and the full decaying <span class="math inline">\(\gamma_k = 1/(k-K_1)\)</span> takes over, which is what lets the SA estimate settle. Averaging on the variance scale is deliberate — it is the scale the <a href="#scalar-residual-error-update">scalar residual sufficient statistic</a> already averages on, and a geometric mean of a sequence with mass near zero collapses where the arithmetic mean of <span class="math inline">\(\sigma^2\)</span> does not (measured: <span class="math inline">\(\log\sigma\)</span> averaging leaves the #1445 fixture’s <span class="math inline">\(\sigma_{\text{add}}\)</span> at 0.47 against a truth of 1.8, where the <span class="math inline">\(\sigma^2\)</span> average reaches 1.4). The third term is one-sided: σ never steps <em>faster</em> than θ, but the two are not always equal. They are equal during <strong>exploration</strong> whenever <code>mstep_damping</code> is at or below 0.2 (the <code>iiv_on_ruv</code> default of 0.03 is), and from the fifth convergence iteration on, where <span class="math inline">\(1/(k-K_1) \le 0.2\)</span>. They differ over the four hand-off iterations <span class="math inline">\(k-K_1 \in \{1,2,3,4\}\)</span> — θ takes 1, ½, ⅓, ¼ while σ takes 0.2 — and during exploration for any <code>mstep_damping</code> above 0.2, where σ is the slower of the two. So no configuration, <code>iiv_on_ruv</code> included, is bit-identical to before; what is preserved is that σ is never given a larger step than the θ it shares a maximiser with.</p>
</section>
<section id="m-step-for-omega-closed-form" class="level3">
<h3 class="anchored" data-anchor-id="m-step-for-omega-closed-form">3. M-Step for Omega (Closed Form)</h3>
<p><span class="math display">\[
\Omega_k = S_2
\]</span></p>
<p>with structurally-zero entries (cross-block off-diagonals, standalone-vs-block off-diagonals, and all off-diagonals in a fully-diagonal Ω) zeroed out — the SA accumulator <span class="math inline">\((1/N) \sum_i \eta_i \eta_i^T\)</span> is dense by construction, but the model declares which entries are free parameters. Without this projection the chain feeds spurious sampling correlations into the next iteration’s MH proposal Cholesky and Ω drifts toward rank-deficiency. Free diagonals are then floored at <code>1e-6</code> to keep them away from zero (which would collapse the per-eta proposal scale <code>δ·chol(Ω)</code>); this floor does not by itself guarantee positive-definiteness of a full block Ω.</p>
<p><strong>Burn-in.</strong> This M-step is suppressed for the first <code>omega_burnin</code> iterations (default 20, clamped to <code>n_exploration</code>): Ω is held at its starting value while the MH chain warms up. The MH proposal scale is <span class="math inline">\(\delta_i \cdot \mathrm{chol}(\Omega)\)</span>, so Ω and the sampler are coupled. On sparse data (few observations per subject) a cold-start chain (η = 0, only <code>n_mh_steps</code> proposals) produces a tiny <span class="math inline">\((1/N) \sum_i \eta_i \eta_i^T\)</span>; with <span class="math inline">\(\gamma_1 = 1\)</span> the M-step would install that as Ω on iteration 1, shrinking the proposal, which keeps the chain near zero — a self-reinforcing collapse that dumps between-subject variability into the residual error. The SA statistic <span class="math inline">\(S_2\)</span> is still refreshed each burn-in iteration (at the damped rate <span class="math inline">\(\gamma_k^\Omega\)</span>, so it is a running average of the warming chain), so the first Ω update after burn-in reflects the warmed-up chain rather than the cold-start spread. Set <code>omega_burnin = 0</code> to disable the burn-in; note that the damped Ω step above now also guards this cold-start collapse on its own (it is a strict generalisation — continuous rather than for the first <code>omega_burnin</code> iterations only), so disabling the burn-in no longer reproduces the collapse by itself.</p>
</section>
<section id="4-m-step-for-theta-and-sigma-optimization" class="level3">
<h3 class="anchored" data-anchor-id="4-m-step-for-theta-and-sigma-optimization">4. M-Step for Theta and Sigma (Optimization)</h3>
<p>Minimize the conditional observation negative log-likelihood with ETAs held fixed:</p>
<p><span class="math display">\[
\sum_{i=1}^{N} \sum_{j=1}^{n_i} \left[ \frac{1}{2} \log V_{ij} + \frac{1}{2} \frac{(y_{ij} - f_{ij})^2}{V_{ij}} \right]
\]</span></p>
<section id="saem-mstep-closed-form" class="level4">
<h4 class="anchored" data-anchor-id="saem-mstep-closed-form">Closed-form EM update for mu-referenced thetas</h4>
<p>When <code>mu_referencing = true</code> (the default), ferx detects mu-referenced parameters from the <code>[individual_parameters]</code> block and applies the <strong>closed-form EM update</strong> for those thetas instead of running NLopt:</p>
<p><span class="math display">\[
g(\theta_j) \leftarrow g(\theta_j) + \gamma_k \cdot \overline{\eta_j}
\]</span></p>
<p>where <span class="math inline">\(\overline{\eta_j} = (1/N) \sum_i \eta_{i,j}\)</span> is the empirical mean of the post-MH random effects for the eta paired with <span class="math inline">\(\theta_j\)</span>, and <span class="math inline">\(g\)</span> is the mu-scale link. For a mu-referenced model where <span class="math inline">\(P_i = g^{-1}(g(\theta) + \eta_i)\)</span> with <span class="math inline">\(\eta_i \sim N(0, \omega^2)\)</span>, this is exactly the M-step that maximises the complete-data log-likelihood, scaled by the SA step size <span class="math inline">\(\gamma_k\)</span> — and it is <em>link-independent</em>: the same shift is the maximiser for <span class="math inline">\(g = \log\)</span>, <span class="math inline">\(g = \mathrm{id}\)</span> and <span class="math inline">\(g = \mathrm{logit}\)</span> alike. After the update the etas are re-centred by the same shift so they remain deviations from the new <span class="math inline">\(g(\theta_j)\)</span>.</p>
<p>What decides eligibility is therefore not the link but whether the <strong>packed</strong> theta — the quantity the optimiser actually steps — <em>is</em> <span class="math inline">\(g(\theta)\)</span>. ferx packs a theta as <span class="math inline">\(\log \theta\)</span> when its lower bound is non-negative and as <span class="math inline">\(\theta\)</span> otherwise, so:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 42%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Form</th>
<th>mu scale <span class="math inline">\(g(\theta)\)</span></th>
<th>Closed-form EM update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>P = THETA * exp(ETA)</code>, <code>exp(log(THETA) + ETA)</code></td>
<td><span class="math inline">\(\log \theta\)</span></td>
<td>yes (theta is log-packed)</td>
</tr>
<tr class="even">
<td><code>P = inv_logit(THETA + ETA)</code></td>
<td><span class="math inline">\(\theta\)</span></td>
<td>yes — a logit-scale theta has a negative lower bound, so it is packed as-is (#918)</td>
</tr>
<tr class="odd">
<td><code>P = inv_logit(logit(THETA) + ETA)</code></td>
<td><span class="math inline">\(\mathrm{logit}\,\theta\)</span></td>
<td>no — no packing has that scale</td>
</tr>
<tr class="even">
<td><code>P = THETA + ETA</code></td>
<td><span class="math inline">\(\theta\)</span></td>
<td>no — routed to NLopt</td>
</tr>
</tbody>
</table>
<p>The two excluded forms are still mu-referenced (they still centre the inner/E-step search); they just take the numeric M-step. This matters most for bounded <span class="math inline">\((0,1)\)</span> parameters — bioavailability, pathway fractions, <span class="math inline">\(E_{max}\)</span> fractions — in models that also carry IIV on the residual error, where the numeric M-step works from noticeably noisier conditional samples: declare the theta on the logit scale (<code>theta LOGIT_F(-0.477, -10.0, 10.0)</code>) and write <code>F = inv_logit(LOGIT_F + ETA_F)</code>.</p>
<p>The packing rule cuts both ways, and a mismatch is reported rather than silently routed: a lognormal theta declared with a <em>negative</em> lower bound is packed on the identity scale, and a logit-scale theta declared with a <em>non-negative</em> lower bound (<code>theta LOGIT_F(0.5, 0.0, 5.0)</code>) is packed on the log scale. Neither packed value is the mu, so the closed form does not apply; SAEM and IMP/IMPMAP estimate such a theta through the numerical M-step and emit an advisory naming it, with the bound to change. Under <code>mu_referencing = false</code> <strong>SAEM</strong> runs no closed-form shift at all and suppresses the advisory; single-population IMP/IMPMAP is different — its shift is EM-mandatory, so it runs (and advises) independently of that option, as <a href="../estimation/impmap.html">the IMP/IMPMAP page</a> describes.</p>
<p>A theta that anchors <strong>more than one</strong> eta (<code>F1 = inv_logit(LOGIT_F + ETA_F1)</code> <em>and</em> <code>F2 = inv_logit(LOGIT_F + ETA_F2)</code>, or the lognormal <code>CL = TVP*exp(ETA_CL)</code> / <code>V = TVP*exp(ETA_V)</code>) is also routed to the numerical M-step with an advisory: the closed form shifts a packed theta by one eta mean and pins it, and no single such shift is the joint maximiser. Give each eta its own typical value to get the closed-form update.</p>
<p>NLopt still runs for any remaining thetas (non-mu-referenced); the closed-form-updated thetas are pinned at their new values for the NLopt call.</p>
</section>
<section id="saem-mstep-covariate-mu-ref" class="level4">
<h4 class="anchored" data-anchor-id="saem-mstep-covariate-mu-ref">Covariate mu-references: typical values that read several thetas</h4>
<p>A typical value that reads <strong>two or more</strong> thetas has no single anchor:</p>
<pre><code>CL = (TVCL + (CRCL - 90) * TH_CRCL) * exp(ETA_CL)   # additive covariate
CL = TVCL * (WT / 70) ^ TH_WT * exp(ETA_CL)           # estimated exponent
F  = inv_logit(LOGIT_F + TH_SEX * SEX + ETA_F)        # logit-scale covariate</code></pre>
<p>Before <a href="https://github.com/FeRx-NLME/ferx-core/issues/619">#619</a> every theta in such a value sat on the numerical M-step, which holds each subject’s sampled η fixed. That is the wrong coordinate system for a covariate slope: once the MH sampler has let η absorb the covariate-correlated part of the between-subject variation, the slope sees almost no gradient, and the two drift together — on the fluconazole model of #619 the renal gradient reached its bound at 0.</p>
<p>ferx now records such a value as a <strong>covariate mu-reference</strong> (all its thetas, one eta) and gives it the mu-referencing M-step in its general form. Holding each subject’s <span class="math inline">\(\phi_i = g(A_i(\theta)) + \eta_i\)</span> fixed, the group’s thetas are re-fitted to the population of individual values:</p>
<p><span class="math display">\[
\hat\theta = \arg\min_\theta \; \sum_i \tfrac12\,(\phi_i - g(A_i(\theta)))^\top \Omega^{-1} (\phi_i - g(A_i(\theta))) \;+\; \sum_i -\log p(y_i \mid \phi_i, \theta)
\]</span></p>
<p>with <span class="math inline">\(A_i\)</span> the eta-free typical value at subject <span class="math inline">\(i\)</span>’s covariates and <span class="math inline">\(g\)</span> the link (<code>log</code> or the logit-scale identity). The data term drops out — and the step is an exact nonlinear least-squares fit (Gauss–Newton) — when three things hold: every covariate the value reads is <strong>constant within each subject</strong>, no estimated theta of the group is read <strong>anywhere else in the model</strong>, and no <em>other</em> individual parameter reads the group’s <strong>eta</strong>. Otherwise the term stays live and the sum is minimised numerically (BOBYQA), still in the <span class="math inline">\(\phi\)</span>-frozen coordinates. A covariate that <strong>varies within a subject</strong> leaves a <span class="math inline">\(\theta\)</span>-dependence through the within-subject ratio <span class="math inline">\(A_i(t)/A_i(t_0)\)</span>; a theta the model reuses — <code>CL = (TVCL + TH_X*WT) * exp(ETA_CL)</code> alongside <code>V = TVV + TH_X</code> — leaves one through that other parameter, since preserving <span class="math inline">\(\phi_{CL}\)</span> pins <code>CL</code> but not <code>V</code>; an eta the model reuses — the same <code>CL</code> alongside <code>V = TVV * exp(0.5*ETA_CL)</code> — leaves one through the re-centring, which holds <span class="math inline">\(\phi_{CL}\)</span> fixed but moves <code>V</code>. ferx detects both kinds of reuse and says so in a fit warning naming the theta or the eta. The new estimate is blended with the same SA step <span class="math inline">\(\gamma_k\)</span> as the single-anchor shift, and each η is re-centred by the change in its own mu so <span class="math inline">\(\phi_i\)</span> is unchanged. This is NONMEM’s <code>MU_1 = LOG(THETA(1) + (CRCL-90)*THETA(2))</code> — a MU that is nonlinear in THETA — done automatically.</p>
<p>Covariate mu-references that <strong>share an estimated theta</strong> are one group (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1620">#1620</a>). In <code>examples/two_cpt_oral_cov.ferx</code>, <code>CL</code> and <code>V1</code> both read <code>THETA_WT</code>. Stepping them one at a time cannot work: a step over CL’s thetas alone holds <span class="math inline">\(\eta_{V1}\)</span> as drawn — the η-frozen coordinates #619 removed for a single typical value — so <span class="math inline">\(\phi_{V1}\)</span> absorbs V1’s half of every move of <code>THETA_WT</code>, and the exponent drifts to its bound (SAEM put it at 0.0101 against NONMEM’s 0.662). The joint step fits the union of the thetas to every member’s <span class="math inline">\(\phi_i\)</span> under the full <span class="math inline">\(\Omega^{-1}\)</span> form and re-centres every member’s eta. A theta read only by the members is not “read elsewhere”, so such a group still takes the exact engine; one also read outside every group, or by a mu-reference that was itself declined, keeps the data term. A fit warning names the etas and the shared theta. A shared <code>FIX</code>ed theta links nothing.</p>
<p>A covariate mu-reference is used by SAEM and IMP/IMPMAP only; <code>mu_refs</code> (inner-loop centring, <code>suggest_start</code>, reporting) is unchanged, so FOCE/FOCEI/Laplace fits are byte-identical with and without one. It is declined — with a warning naming the thetas, which then stay on the numerical M-step as before — when one of its thetas is also another eta’s single anchor, when the eta’s initial IIV is below <code>1e-3</code>, when every theta of the group is <code>FIX</code>ed, under a mixture model, and under <code>mu_referencing = false</code>. A group step also stands down for one iteration when the typical value is not finite for some subject at the current θ — an additive form such as <code>TVCL + (CRCL-90)*TH_CRCL</code> can go ≤ 0 for a low-covariate subject — and the fit reports how many iterations that happened on, since the thetas were then moved by the numerical M-step (or, under IMP/IMPMAP, left to it) rather than by the group. A value that reads <code>TIME</code>, <code>MIXNUM</code>, a second eta, or a local variable that is assigned conditionally is not recorded at all.</p>
</section>
<section id="scalar-residual-error-update" class="level4">
<h4 class="anchored" data-anchor-id="scalar-residual-error-update">Scalar residual-error update</h4>
<p>For a single, free additive or proportional residual SD in a single-population, uncensored Gaussian model whose free structural thetas are all log-mu-referenced, SAEM also averages the residual sufficient statistic instead of replacing the SD with the latest MCMC draw’s conditional optimum. For additive error it stores</p>
<p><span class="math display">\[
S_r \leftarrow (1-\gamma_k)S_r + \gamma_k\sum_{ij}(y_{ij}-f_{ij})^2,
\qquad \sigma = \sqrt{S_r/n_{\mathrm{obs}}}.
\]</span></p>
<p>For proportional error, the summand is divided by <span class="math inline">\(f_{ij}^2\)</span>. This reduces otherwise persistent final-draw Monte Carlo noise in the residual SD. It is an internal exact M-step for that restricted likelihood, not a new fit option. Combined or multi-endpoint error, <code>block_sigma</code>, M3 censoring, IOV, <code>iiv_on_ruv</code>, FREM, custom residual magnitude, log-transform-both-sides, mixtures, fixed residual SDs, and models with a free numerical structural theta continue to use the general NLopt M-step.</p>
</section>
<section id="saem-mstep-bobyqa" class="level4">
<h4 class="anchored" data-anchor-id="saem-mstep-bobyqa">The NLopt M-step (BOBYQA)</h4>
<p>The NLopt M-step uses <strong>BOBYQA</strong> (derivative-free trust-region with quadratic interpolation). The earlier gradient-based SLSQP path was found to lock onto one side of the Emax-Hill identifiability ridge on the dense-Emax PKPD benchmark (under-estimating EMAX by ~40% at virtually identical OFV); BOBYQA’s quadratic trust-region exploration lands much closer to truth and ~40% faster on that benchmark (no FD-gradient eval per parameter), while remaining numerically equivalent (ΔOFV &lt; 0.1) on simpler PK-only models.</p>
<p>When <code>mu_referencing = false</code>, the full NLopt M-step runs for all thetas as before.</p>
</section>
<section id="saem-mstep-no-closed-form" class="level4">
<h4 class="anchored" data-anchor-id="saem-mstep-no-closed-form">Thetas the closed-form update cannot reach</h4>
<p>Two model shapes leave a theta on the numerical M-step. The first is slower; the second can bias the estimate outright.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Non-mu-referenced parameters slow SAEM convergence
</div>
</div>
<div class="callout-body-container callout-body">
<p>Whenever the estimation chain runs SAEM, ferx warns if any individual parameter’s random effect is <strong>not</strong> mu-referenced — for example <code>CL = TVCL + ETA_CL</code> instead of <code>CL = TVCL * exp(ETA_CL)</code>. Such parameters cannot use the closed-form EM update above and fall back to the slower NLopt M-step, which can strongly slow convergence. (A typical value that reads several thetas, such as an additive covariate model, is <em>not</em> in this class since #619 — see <a href="#saem-mstep-covariate-mu-ref">covariate mu-references</a>.) The warning fires independently of the <code>mu_referencing</code> fit option: turning the option off does not remove the risk — it removes the mu-centering that mitigates it — so the diagnostic is most warranted in exactly that case. Prefer log-mu-referenced forms (<code>P = TV * exp(ETA)</code>), or, for a parameter bounded to <span class="math inline">\((0,1)\)</span>, the logit-scale form <code>P = inv_logit(LOGIT_P + ETA_P)</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A theta with no ETA at all rides a different, noisier update
</div>
</div>
<div class="callout-body-container callout-body">
<p>The warning above covers a parameter whose eta ferx could not mu-reference. A <strong>fixed-effect-only theta</strong> — one that carries no eta anywhere in <code>[individual_parameters]</code> — is a distinct case, and SAEM warns about it separately:</p>
<pre><code>SAEM: estimated parameter(s) [TVFRD1] have NO associated ETA, so they are not
mu-referenced and are moved only by the η-frozen numerical M-step. ...</code></pre>
<p>Such a theta never receives the closed-form <code>log θ += γ·mean(η)</code> shift, which is an exact Robbins-Monro average. Its only channel is the numerical M-step, which re-maximises the conditional observation likelihood against each iteration’s MCMC η draw and assigns the maximiser. That is a valid stochastic-EM update — its fixed point is the marginal optimum whenever the E-step samples the right conditional — but it is noisier than the closed-form shift, it runs only every third exploration iteration, and on a poorly mixing chain it can settle away from the marginal optimum (see the FREM case below).</p>
<p>Before 0.4.x (#1415) this channel was broken in a way that read as “biased”: the NLopt solve behind it started from a first design a quarter of the bound range wide (×12–×26 of the current value on the default bounds) and stopped on a <code>1e-4</code> relative tolerance, so it returned a few percent of a step; and #1011 had then blended even that at 3 % per exploration M-step. The result was a theta that travelled a small fraction of the way to the optimum and stopped, on every model with such a theta — allometric and maturation exponents, covariate slopes, inter-compartmental clearances. Both are fixed: the solve starts local and converges, and the exploration cap is off by default (it is kept only for <code>iiv_on_ruv</code> models — see the next section).</p>
<p>Measured on the three <code>ferx-testdata</code> models of #1415, importance-sampled −2 log L at the final estimates (lower is better; the IS readout, not the FOCE approximation the fit YAML reports — see below):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>model (no-ETA thetas)</th>
<th style="text-align: right;">before</th>
<th style="text-align: right;">after</th>
<th style="text-align: right;">reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>melphalan (<code>TVQ</code>, <code>CL_CRCL</code>)</td>
<td style="text-align: right;">2705.8</td>
<td style="text-align: right;">2684.0</td>
<td style="text-align: right;">NONMEM SAEM 2682.4</td>
</tr>
<tr class="even">
<td>clofarabine (<code>TVQ</code>, <code>TVV2</code>, <code>THALF</code>)</td>
<td style="text-align: right;">17778.5</td>
<td style="text-align: right;">17764.3</td>
<td style="text-align: right;">NONMEM SAEM 17734.6</td>
</tr>
<tr class="odd">
<td>thiotepa (nine of eleven thetas)</td>
<td style="text-align: right;">6047.8</td>
<td style="text-align: right;">5827.3</td>
<td style="text-align: right;">IS at the FOCEI optimum 5823.6</td>
</tr>
</tbody>
</table>
<p>On thiotepa every no-ETA theta had ended within a few percent of its initial value; after the fix they land where FOCEI lands. The in-repo anchor is <code>covmuref_power</code> with the weight covariate routed through an <code>if</code> block so the #619 group detection does not apply and <code>TH_WT</code> rides this channel: NONMEM SAEM 0.921, ferx 0.332 before (its 0.3 start) and 0.961 after.</p>
<p>Two structural remedies remain better than this channel where they apply:</p>
<ul>
<li><strong>Attach an eta</strong> — <code>P = TVP * exp(ETA_P)</code> with a small omega (optionally <code>FIX</code>). ferx then mu-references it automatically and the exact closed-form update takes over.</li>
<li><strong>Write a covariate model in a form #619 can see</strong> — a covariate read from the data directly, not through a conditionally assigned local — so the slope joins the typical value’s mu-reference group.</li>
</ul>
<p>Otherwise cross-check against <a href="../estimation/foce.html">FOCEI</a> or <a href="../estimation/impmap.html">IMPMAP</a>, which do not depend on this channel.</p>
</div>
</div>
</section>
</section>
<section id="saem-mstep-jensen" class="level3">
<h3 class="anchored" data-anchor-id="saem-mstep-jensen">Averaging a maximiser is not maximising the average</h3>
<p>The numerical M-step re-maximises the frozen-η objective against <strong>one</strong> draw and then adopts that maximiser. A maximiser is a nonlinear function of the draw, so what the run converges to is <code>E[θ*(η)]</code> rather than the <code>θ</code> that maximises <code>E[Q(θ, η)]</code> — SAEM’s actual target. The difference is a Jensen-type bias that grows with the dispersion of the draws, which is why it gets <em>worse</em> when the E-step samples better (#1458).</p>
<p>It is invisible in the trace: the objective is fine, and only a comparison against a long-run reference or a FOCEI fit shows it. Two opt-in alternatives attack it: one <strong>removes</strong> the Jensen term by never forming a maximiser, the other <strong>shrinks</strong> it by averaging more draws into the one it forms. Both are <strong>off by default</strong>, and a fit that sets neither is bit-identical to before.</p>
<section id="the-two-alternatives" class="level4">
<h4 class="anchored" data-anchor-id="the-two-alternatives">The two alternatives</h4>
<dl>
<dt><code>mstep_solver = score_sa</code></dt>
<dd>
Solves the score equation <code>E[∇Q(x, η)] = 0</code> by stochastic approximation, preconditioned by the SA-averaged expected information (Kuhn &amp; Lavielle 2005):
<pre><code>I_k = (1 − γ_k)·I_{k−1} + γ_k·I(x_k, η_k)
x_{k+1} = x_k − γ_k·(I_k + λ·diag I_k)⁻¹·∇Q(x_k, η_k)</code></pre>
A fixed point needs <code>E[∇Q(x*, η)] = 0</code>, which is the stationarity condition of the averaged objective, so no Jensen term arises. σ takes the same Newton <em>direction</em> as every other coordinate, but the step gives it a <strong>target</strong> that <code>damp_mstep_sigma_variance</code> then moves it a <code>γ_σ = min(γ, 0.2, γ_mstep)</code> fraction of the way to, on the variance scale — the same <a href="https://github.com/FeRx-NLME/ferx-core/issues/1445">#1445</a> policy the derivative-free arms use, not a second copy of it. That is a smaller <em>gain</em> on the step, not the blend stacked on top of it (which really would move σ at <code>γ²</code>). One gradient sweep is cheaper than the <code>mstep_maxiter·(n+1)</code> population passes the derivative-free solve costs, so this M-step runs every iteration rather than every third during exploration.
</dd>
<dt><code>mstep_draws = K</code></dt>
<dd>
Averages the <em>derivative-free</em> M-step objective over this iteration’s η draw and the previous <code>K − 1</code> iterations’ draws, so the maximiser NLopt returns is the maximiser of an average. The bias falls roughly as <code>1/K</code> — it shrinks, it does not go away — at <code>K</code> times the M-step’s objective evaluations, and only to the extent that consecutive draws decorrelate, which under the default sticky random-walk E-step they largely do not. Ignored under <code>score_sa</code>.
</dd>
</dl>
<p>Both are restricted to the plain Gaussian residual scope the expected information has a closed form on: no IOV, no <a href="../estimation/mixture.html">mixture</a>, no M3, no time-to-event endpoint, no <code>block_sigma</code> residual correlation, no <code>[covariate_nn]</code> θ, no residual magnitude, no FREM. A model outside it keeps the historical solver and says so by name in the fit’s warnings.</p>
</section>
<section id="measured" class="level4">
<h4 class="anchored" data-anchor-id="measured">Measured</h4>
<p>On the busulfan benchmark of #1458 (<code>ferx-testdata/busulfan_dominic</code>, 600 subjects, analytic 2-cpt IV, <code>block_omega(ETA_CL, ETA_V1)</code> + <code>omega ETA_V2</code>, combined error, <code>TVQ</code> with no ETA), 6 seeds at the default 150/250/20 schedule, on the importance-sampled −2 log L — the neutral readout, since a SAEM fit has no objective of its own. <code>B6qfix</code> is the same model with <code>TVQ</code> held <code>FIX</code>, which removes this channel and nothing else:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><code>TVQ</code> free</th>
<th><code>TVQ</code> FIX</th>
<th>what a free no-ETA θ costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>default (<code>bobyqa</code>)</td>
<td>60044.87 ± 3.29</td>
<td>60035.12 ± 2.08</td>
<td><strong>+9.75</strong></td>
</tr>
<tr class="even">
<td><code>mstep_solver = score_sa</code></td>
<td>60034.59 ± 5.27</td>
<td>60031.22 ± 3.35</td>
<td><strong>+3.37</strong></td>
</tr>
<tr class="odd">
<td><code>mstep_draws = 2</code></td>
<td>60043.87 ± 3.77</td>
<td>60034.62 ± 3.45</td>
<td>+9.25</td>
</tr>
<tr class="even">
<td><code>mstep_draws = 3</code></td>
<td>60045.61 ± 2.36</td>
<td>60033.99 ± 3.50</td>
<td>+11.62</td>
</tr>
</tbody>
</table>
<p><code>score_sa</code> removes about two-thirds of the penalty, at the same cost (6.40 against 6.47 CPU-seconds: one gradient sweep every iteration in place of a derivative-free solve every third). <code>mstep_draws</code> does not move it at all here and costs 53 % (<code>K = 2</code>) to 89 % (<code>K = 3</code>) more CPU — consecutive draws of the default random-walk E-step are too correlated for a two- or three-draw average to be worth anything, which is the regime #1458 predicted it would fail in. It is kept because that argument is about the <em>kernel</em>, not about the estimator, and a near-i.i.d. kernel changes it.</p>
<p>On the 100-subject subset the three arms are a tie (7531.37 ± 0.37 default against 7531.14 ± 0.93 for <code>score_sa</code>), with <code>score_sa</code>’s seed spread 2.5× wider.</p>
</section>
<section id="why-score_sa-is-not-the-default" class="level4">
<h4 class="anchored" data-anchor-id="why-score_sa-is-not-the-default">Why <code>score_sa</code> is not the default</h4>
<p>It was a candidate in <a href="https://github.com/FeRx-NLME/ferx-core/issues/1449">#1449</a> and it is not a close call on either side, which is why the answer is worth recording.</p>
<p><strong>For.</strong> Re-measured at today’s shipped defaults (<code>n_mh_steps = auto</code>) over all eight SAEM benchmarks, 6 seeds each, single-threaded, it is tie-or-better than <code>bobyqa</code> on the importance-sampled −2 log L on every one — best on busulfan (−5.14), busulfan-<code>TVQ</code>-FIX (−5.58) and the thiotepa ODE bench (−11.07) — and it costs <strong>25–54 % less CPU</strong> (cefepime 5.36 → 2.45 s, thiotepa 215 → 94 s), because one gradient sweep per iteration replaces a derivative-free solve whose cost is <code>mstep_maxiter·(n+1)</code> population passes.</p>
<p><strong>Against — the σ half, fixed in <a href="https://github.com/FeRx-NLME/ferx-core/issues/1480">#1480</a>.</strong> As #1458 shipped it, <code>score_sa</code> stepped σ at the shared γ and in packed (log σ) units, which is #1445’s two defects at once: during exploration <code>γ = 1</code>, so that is a <em>full</em> Newton step to one draw’s score root with no Robbins-Monro averaging, and a log-scale blend is a geometric mean of the σ sequence. On the sparse combined-error fixture of #1445 — 300 subjects with a median of one observation each, truth <code>combined(prop = 0.13, add = 1.8)</code> — it scattered the <em>minority</em> additive σ. Measured seeds 1 / 2 / 3, <code>ci-test</code>, aarch64:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><code>ADD_ERR</code> (truth 1.8)</th>
<th>cross-seed sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>bobyqa</code> (the default)</td>
<td>1.33 / 1.83 / 2.17</td>
<td>0.42</td>
</tr>
<tr class="even">
<td><code>score_sa</code> as #1458 shipped it</td>
<td><strong>0.84 / 0.52 / 1.13</strong></td>
<td>0.31</td>
</tr>
<tr class="odd">
<td><code>score_sa</code> with the γ_σ schedule only</td>
<td>0.87 / 0.99 / 1.20</td>
<td>0.17</td>
</tr>
<tr class="even">
<td><code>score_sa</code> after #1480</td>
<td>1.90 / 1.86 / 2.11</td>
<td>0.14</td>
</tr>
</tbody>
</table>
<p>The third row is why the fix is both halves: the schedule alone still leaves seed 1 at 0.87, under the factor-of-two gate of 0.9. The objective could not see any of it — the FOCE readout differs by under 2 units across all those fits, and the benchmark suite’s −2 log L prefers <code>score_sa</code> throughout. This is the same channel #1445 is about, a variance component identified only where <code>σ_add</code> and <code>σ_prop·f</code> are comparable, and it is why <code>tests/saem_combined_error.rs</code> scores it against <strong>simulation truth</strong> rather than against another estimator.</p>
<p><strong>Against — the θ half, still open (#1480).</strong> On the #619 <code>covmuref_power</code> anchor, whose <code>TH_WT</code> carries no ETA and therefore moves only through this channel, <code>score_sa</code> at the default 150/250 schedule reaches <strong>0.746</strong> against NONMEM SAEM’s 0.921 — outside the 0.12 window the default solver satisfies. It is slow rather than wrong: at 300/700 it lands at <strong>0.9845</strong> (|Δ| 0.063) while <code>bobyqa</code> at that same schedule <em>overshoots</em> to 1.1485 (|Δ| 0.227). So the window is a property of the estimator and the schedule together, and <code>score_sa</code> needs a longer run on a θ that starts far from its optimum. <code>tests/saem_covariate_mu_ref.rs</code> keeps the anchor at 300/700 live and gates the default-schedule arm on the open issue.</p>
<p>A default has to be safe for the parameter the likelihood barely constrains and has to converge in the schedule it ships with, so <code>score_sa</code> stays opt-in. It is worth reaching for on a model with a free θ that has no ETA, with a longer schedule than the default if that θ starts far away.</p>
<p>One further thing #1449 measured: <code>score_sa</code>’s score/information sweep does not reuse the cached event schedule, so on a model whose <code>[individual_parameters]</code> read <code>TIME</code> or a time-varying covariate it rebuilds two schedules per subject per iteration. That is an unrealised saving on top of the CPU numbers above, not a regression against them.</p>
<p>Two things the numbers do <strong>not</strong> say. First, <code>d_final</code> against a long-run reference gets <em>worse</em> under <code>score_sa</code> (<code>TVQ</code> moves from −0.04 to −0.18 log units away from it) — but that reference is the same estimator run longer, so it carries the same bias, and it cannot arbitrate a change that removes it. Second, a FOCEI fit of the same model is not the oracle either: its own importance-sampled −2 log L is 60046.43, worse than every SAEM arm above, so it locates <code>TVQ</code> (7.60) no better than they do.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Neither is a substitute for attaching an ETA
</div>
</div>
<div class="callout-body-container callout-body">
<p>A θ that carries a random effect gets the exact closed-form Robbins-Monro shift and never enters this channel at all. Both options above make the numerical channel unbiased in the limit; the closed form is exact at every iteration. Where the model can be written so #619’s <a href="#saem-mstep-covariate-mu-ref">covariate mu-references</a> apply, that remains the better fix.</p>
</div>
</div>
</section>
</section>
<section id="what-saem-does-about-it-now" class="level3">
<h3 class="anchored" data-anchor-id="what-saem-does-about-it-now">The exploration cap (<code>mstep_damping</code>) is a hold, not a cure</h3>
<p><code>mstep_damping</code> blends the numerical M-step result in as <code>θ ← θ + γ_θ·(θ* − θ)</code> during exploration, with <code>γ_θ</code> capped at the value you set, and averages it at <code>γ = 1/(k−k1)</code> in convergence. <strong>It is off by default</strong> (<code>1.0</code>, plain assignment in both phases) for every model except one with <code>iiv_on_ruv</code>, which keeps the 0.03 cap — the reason is measured below:</p>
<pre><code>[fit_options]
  method        = saem
  mstep_damping = 0.03   # opt in: hold the no-ETA thetas near their start</code></pre>
<p>It was introduced by #1011 at a default of 0.03 after a FREM <code>iiv_on_ruv</code> model (475 subjects, 12 etas) whose absorption-split fraction <code>TVFRD1</code> (<code>D1 = MAT*(1-TVFRD1)</code>, <code>KA = 1/(MAT*TVFRD1)</code>, no eta of its own) drifted from 0.383 to 0.039 under the undamped update, while IMP (0.311), IMPMAP (0.318) and NONMEM IMP (0.394) agree. The capped fit ended at 0.29–0.36, which read as “landing on the marginal optimum”. #1415 measured what the cap does, with the M-step solver repaired:</p>
<ul>
<li><strong>It holds the theta where it starts.</strong> On the same reprex: 0.383 → 0.361, and from a deliberately wrong 0.2 start, 0.2 → 0.191. Its good answer was the model’s initial estimate, which that auto-generated model had taken from a FOCEI fit.</li>
<li><strong>It freezes every other no-ETA theta the same way</strong>, because the cap divides the number of EM steps the exploration phase amounts to (50 M-steps × cap), and a covariate slope confounded with an eta needs all of them. <code>covmuref_power</code> <code>TH_WT</code> (NONMEM 0.921, start 0.3): cap 0.03 → 0.323, 0.1 → 0.340, 0.3 → 0.403, off → 0.961. Thiotepa (IS −2 log L, optimum 5824): 0.03 → 5928, 0.1 → 5897, 0.3 → 5860, off → 5827.</li>
<li><strong>The convergence-phase Robbins-Monro average hurts too.</strong> <code>γ = 1/(k−k1)</code> is the right average for a statistic that is stationary around the optimum, but the sequence of η-frozen maximisers is an EM trajectory, so averaging it weights the early, still-crawling iterates most (<code>TH_WT</code> 0.637 with the average, 0.961 without).</li>
</ul>
<p>The FREM drift itself is real and is <strong>not</strong> fixed: undamped, that reprex settles near <code>TVFRD1</code> 0.18 from either start on the default schedule, keeps drifting on a 3× longer one (0.03), and 200 MH steps per iteration do not change it — so it is not plain E-step under-mixing. The importance-sampled objective cannot rank the two points on a 12-eta model (ESS/K = 0.001), but the FOCEI objective can: the drifted fit is 47 units worse than the held one (7492.7 against 7445.3), so on this model the hold is the better answer.</p>
<p>The drift is the <strong><code>iiv_on_ruv</code> coupling</strong>, not FREM and not the no-ETA channel as such: the same model with its <code>iiv_on_ruv</code> line and <code>ETA_RUV</code> omega removed lands undamped at <code>TVFRD1</code> 0.414, <code>TVMAT</code> 2.680, <code>TVV</code> 137.6 — on NONMEM IMP’s 0.394 / 2.680 / 133.8 — where the 0.03 cap leaves it at 0.342 / 2.228 / 147.5. Under <code>iiv_on_ruv</code> the E-step is modified (<code>η_RUV</code> is re-centred into σ every iteration) and σ shares the numerical M-step with the no-ETA thetas; that is where the pathology lives, and it needs its own fix (#1421). So <strong>the default is keyed to that shape</strong>: a model with <code>iiv_on_ruv</code> keeps the 0.03 cap, every other model runs undamped, and a value you set wins either way. <code>FIX</code> is the honest spelling of the same hold when the value is known.</p>
<p>The option only acts on the channel it is about: a fit is damped when NLopt is left estimating a theta that is <strong>not mu-referenced</strong>, which is exactly the situation the advisory above warns about. A theta that is <code>FIX</code>, that is pinned out by the mu-reference shift, or that is mu-referenceable at all is left on the undamped update, and setting <code>mstep_damping</code> on a model where no theta trips the gate warns that it has no effect rather than accepting it silently. <strong>Sigma takes the same step as theta</strong> when the cap applies, because the numerical M-step is a single NLopt problem over <code>[θ; σ]</code> and a partial step on one component alone would be inconsistent. Under <code>mu_referencing = false</code> a theta written in a mu-referenceable form is not this channel either, so such a fit keeps the undamped update and the option reports no effect.</p>
<p><a href="../estimation/mixture.html">Mixture models</a> are excluded outright: a <code>MIXNUM</code>-switched typical value goes through the same numerical M-step, but its class typical values must <em>separate</em> from a common start, and damping that excursion stalls the separation. For the same reason the mixture arm also keeps the pre-#1415 M-step solver configuration: its class typical values come from a hard class draw, and the NONMEM-anchored mixture seed sweep was calibrated on the partial step that configuration returns — a converged per-class solve moves <code>TVCL2</code> from the NONMEM MLE 2.84 to 3.23. An exact M-step on a hard class draw is a different estimator, so that channel changes only with its own anchor.</p>
</section>
<section id="comparing-a-saem-fit-to-focei-read-the-importance-sampled-objective" class="level3">
<h3 class="anchored" data-anchor-id="comparing-a-saem-fit-to-focei-read-the-importance-sampled-objective">Comparing a SAEM fit to FOCEI: read the importance-sampled objective</h3>
<p>The <code>ofv</code> a SAEM fit reports is the FOCE approximation at the final estimates — SAEM has no objective of its own — and until 0.4.x (#1415) a method <em>chain</em> such as <code>method = [saem, imp]</code> computed it <strong>without</strong> the η–ε interaction, while <code>method = saem</code> alone and every FOCEI fit computed it with. On the thiotepa model that is a 175-unit difference at the same estimates, and it was the bulk of the “SAEM is 341 units worse than FOCEI” that #1415 reported. A chain now keeps the interaction flag unless its final stage is <code>foce</code>, as the single-method form always did. When you compare estimators, compare the importance-sampled −2 log L that an <code>imp_eval_only</code> stage prints (<code>IS done. −2 log L = …</code>) or <code>FitResult::importance_sampling</code>, evaluated at each fit’s estimates.</p>
<p>The number of NLopt evaluations saved is stored in <code>FitResult::saem_mu_ref_m_step_evals_saved</code>, accumulated across SAEM iterations as <code>2 × mstep_maxiter × n_mu_ref_pairs</code> per outer step (one finite-difference probe pair per pinned mu-ref dimension, capped at <code>mstep_maxiter</code> NLopt gradient requests). The field is <code>None</code> when mu-referencing is off or method ≠ SAEM.</p>
<p>When <code>n_leapfrog &gt; 0</code>, <code>FitResult::saem_n_subjects_hmc</code> records how many subjects used HMC at least once during the E-step (the remainder used MH fallback). The field is <code>None</code> for MH-only runs. The fit YAML also emits <code>saem_n_subjects_hmc</code> and <code>saem_n_subjects_mh</code> when the field is <code>Some</code>.</p>
</section>
<section id="adaptive-step-sizes" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-step-sizes">5. Adaptive Step Sizes</h3>
<p>The per-subject step scales <span class="math inline">\(\delta_i\)</span> (MH) and leapfrog step sizes (HMC) are adapted toward a target acceptance rate. Which rule does the adapting is set by <code>[fit_options] scale_adaptation</code>.</p>
<p>Target acceptance rates: 40% for the primary block kernel (MH or HMC’s own 65% when <code>n_leapfrog &gt; 0</code>), 44% for the componentwise kernel. The block kernel and the componentwise kernel carry independent per-subject scales, and each η’s componentwise scale is adapted separately.</p>
<section id="scale_adaptation-interval" class="level4">
<h4 class="anchored" data-anchor-id="scale_adaptation-interval"><code>scale_adaptation = interval</code></h4>
<p>Every <code>adapt_interval</code> iterations, from that window’s acceptance rate:</p>
<ul>
<li>above target: increase <span class="math inline">\(\delta_i\)</span> by 10% (up to 5.0)</li>
<li>at or below target: decrease <span class="math inline">\(\delta_i\)</span> by 10% (down to 0.01, or 1e-6 for a componentwise scale)</li>
</ul>
<p><strong>Know its reach.</strong> The factor is fixed, so the total movement available is <code>1.1^n</code> up or <code>0.9^n</code> down over the <code>n</code> times the rule fires — and on the default 150 + 250 = 400 iterations at <code>adapt_interval = 50</code> that is <strong>8</strong> times, i.e.&nbsp;at most ≈2.1× up or ≈0.43× down <em>however far from target the chain is</em>. A model whose optimal step is an order of magnitude below the 0.3 starting value never reaches it. <code>examples/warfarin_saem.ferx</code> is such a model: on the default settings its combined acceptance collapses to 1.6% by iteration 26 and sits at 2–4% for the remaining ~375 iterations against the 40% target (issue #1444).</p>
</section>
<section id="scale_adaptation-robbins_monro-default" class="level4">
<h4 class="anchored" data-anchor-id="scale_adaptation-robbins_monro-default"><code>scale_adaptation = robbins_monro</code> (default)</h4>
<p>A Robbins–Monro step taken <strong>every</strong> iteration, from that iteration’s own rate:</p>
<p><span class="math display">\[\log \delta_i \leftarrow \log \delta_i + c \, k^{-0.6} \, (\hat{a}_k - a^\ast)\]</span></p>
<p>with <span class="math inline">\(c = 1\)</span>, <span class="math inline">\(k\)</span> the 1-based iteration, <span class="math inline">\(\hat{a}_k\)</span> the realised rate and <span class="math inline">\(a^\ast\)</span> the target. The correction is proportional to the discrepancy, so the reach is unlimited, and the <span class="math inline">\(k^{-0.6}\)</span> decay is the diminishing-adaptation condition that keeps an adapting chain valid (Roberts &amp; Rosenthal 2007). The clamps are the same as the interval rule’s.</p>
<p><strong>It is the default since #1449, and it was not always a free win.</strong> What ferx measures directly is the acceptance rate, and on <code>examples/warfarin_saem.ferx</code> at its shipped settings (150 + 250 iterations, <code>n_mh_steps = 20</code>, seed 12345) the combined rate over the last 100 iterations goes from <strong>3.90%</strong> under <code>interval</code> to <strong>42.05%</strong> under <code>robbins_monro</code>, against the 40% target. That much is reproduced by <code>tests/saem_scale_adaptation.rs</code>.</p>
<p>Whether a rate at target makes the <em>estimates</em> better is a separate question, and one this page does not answer from its own runs. The SAEM benchmarking in <a href="https://github.com/FeRx-NLME/ferx-core/issues/1444">issue #1444</a> reported, over 6 seeds on real datasets, that Robbins–Monro roughly halves warfarin’s final-estimate error against a long-run reference, changes little on models whose baseline scale is already near target, and <strong>regressed</strong> pembrolizumab (303 subjects, 4 η) — a model whose acceptance was already <em>above</em> target — by +4.7 on the importance-sampled −2 log L. That regression is what kept the rule opt-in.</p>
<p>It is gone at today’s defaults, and the reason is worth knowing: those measurements were taken at a fixed <code>n_mh_steps = 20</code>, and #1468 made the proposal count <code>auto</code>, which resolves to <strong>6</strong> on that model. Re-measured at the shipped defaults over 6 seeds (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1449">#1449</a>), Robbins–Monro <em>improves</em> pembrolizumab by <strong>−4.7</strong>, and the only bench it costs anything on is vancomycin (+0.98 against a 0.94 cross-seed sd) — which the dead band below removes. #1444’s own data already pointed this way: at <code>n_mh_steps = 8</code> it won on that bench too. These numbers have no NONMEM counterpart (NONMEM’s SAEM exposes no comparable step-scale knob).</p>
<p><code>scale_adaptation = interval</code> restores the historical rule exactly.</p>
<p>The κ (IOV) scales stay on the interval rule under both settings: the per-occasion kernel makes one proposal per occasion per iteration, so a single iteration’s rate for one subject is a ratio of small integers, and the Robbins–Monro arm has not been measured there.</p>
</section>
<section id="scale_deadband-only-correct-a-chain-that-is-off-target" class="level4">
<h4 class="anchored" data-anchor-id="scale_deadband-only-correct-a-chain-that-is-off-target"><code>scale_deadband</code> — only correct a chain that is off target</h4>
<p><code>[fit_options] scale_deadband = &lt;lo&gt;,&lt;hi&gt;</code>, <strong>default <code>0.15,0.60</code></strong>, makes the Robbins–Monro step conditional: it fires only when that iteration’s acceptance is <strong>outside</strong> <code>[lo, hi]</code>, and inside the band the scale is left bit-for-bit alone (there is no interval bump underneath it — the interval rule is off for the whole run under <code>robbins_monro</code>). The band is one absolute acceptance window shared by the block kernel (target 40%) and each componentwise coordinate (44%). It is ignored under <code>scale_adaptation = interval</code>, which has no per-iteration step to skip.</p>
<p>It exists for the failure the previous section names: the models Robbins–Monro was written for sit at 2–4%, and the one it regressed was already <em>above</em> target and got pulled down onto it.</p>
<p><strong>What it does, measured, is not quite what it was built for.</strong> Over the 8-benchmark, 6-seed suite of #1449 the band turns the unbanded rule’s one loss into a win (vancomycin +0.98 → −0.13 on the importance-sampled −2 log L, against a 0.94 cross-seed sd) and keeps most of its gains (pembrolizumab −4.69 → −3.74, warfarin’s rescue intact: tail acceptance 0.041 under <code>interval</code>, 0.422 unbanded, 0.391 banded). But it does <strong>not</strong> leave a near-target chain alone: the realised tail acceptance is <em>lower</em> under the band than without it on every bench measured, because of the fixed-point shift described below. The improvement is real; the mechanism is not “the controller declined to act”.</p>
<p>Two things to know before setting one:</p>
<ul>
<li><p><strong>A wide band freezes the scales; it does not disable the dead band.</strong> The rule fires only outside the band, so a band wider than the spread of the per-iteration rate means no step ever runs. <code>scale_deadband = none</code> (or an empty band, <code>lo == hi</code>) is the spelling that restores plain Robbins–Monro, and a band covering all of <code>[0, 1]</code> is rejected with that message rather than accepted.</p></li>
<li><p><strong>Setting it from Rust is validated too.</strong> <code>FitOptions::saem_scale_deadband</code> is public, so a band can reach the sampler without passing the model-file parser. An empty, reversed, out-of-range or everything-covering band is dropped there — the fit runs the unbanded Robbins-Monro rule and says so in its warnings — so the two front ends cannot produce different numerical behaviour for the same option, and neither can freeze the step scales.</p></li>
<li><p><strong>A band moves the fixed point.</strong> A per-iteration rate is <code>n_accepted / n_proposals</code>, so it is quantised to multiples of <code>1/n_mh_steps</code> (block) or <code>1/n_cw_sweeps</code> (componentwise), and the band censors the small deviations while keeping the tails. Unless the band is symmetric about the target <em>and</em> the rate’s distribution is symmetric, the surviving steps do not cancel at the target: the scale settles where the censored deviations balance, which is not where the unbanded rule settles. With the shipped band and <code>n_mh_steps = 6</code> that equilibrium is near 33% rather than 40%.</p></li>
</ul>
</section>
<section id="acceptance-rate-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="acceptance-rate-diagnostics">Acceptance-rate diagnostics</h4>
<p>Two warnings land in <code>FitResult.warnings</code> (never on stderr), most severe first:</p>
<ul>
<li><p><strong>Not mixing</strong> — the cumulative post-burn-in acceptance is below 1%. The sampled ETAs barely moved, so the M-step ran on degenerate sufficient statistics and Ω/σ are unreliable. The realised tail rate is also available as <code>FitResult::saem_mh_accept_tail</code>, so a script can check mixing without matching on the warning text.</p></li>
<li><p><strong>Persistently far from target</strong> — the acceptance over the <strong>last 100</strong> post-burn-in iterations is outside 10–80%. The band is deliberately wide: a fit at 0.25 or 0.60 is unremarkable, and this is not a range of “good” rates but the range outside which the step scales have demonstrably failed to find their target. The message carries the realised tail rate, the target, the window length and the cumulative rate, so you do not have to re-run with <code>optimizer_trace</code> to see how far off it was. It is the <em>tail</em> rather than the whole-run average that is reported, because a run that mixes badly early and recovers averages to a number describing neither half; and it stays quiet for runs with fewer than 25 post-burn-in iterations, where the realised rate describes the starting scale rather than a failure to reach target.</p></li>
</ul>
</section>
</section>
</section>
<section id="post-saem-finalization" class="level2">
<h2 class="anchored" data-anchor-id="post-saem-finalization">Post-SAEM Finalization</h2>
<p>After the SAEM iterations complete:</p>
<ol type="1">
<li><strong>EBE Refinement</strong>: Run the standard FOCE inner loop (BFGS optimization) warm-started from the SAEM ETAs to obtain final empirical Bayes estimates</li>
<li><strong>Combined-error additive-collapse report</strong>: for <code>combined(PROP, ADD)</code> residual-error models, when SAEM has left a <em>free</em> additive component <code>ADD</code> at or below <code>1e-3</code> — the detection band just above its <code>exp(-8) ≈ 3.35e-4</code> optimizer lower bound — the fit carries a warning saying so. It is a report, not a repair — ferx once ran a FOCEI marginal-likelihood polish here and adopted it if it lowered the OFV, and that silent second fit was removed in favour of the warning. The channel it was papering over is fixed at source: the σ M-step now takes a <a href="#stochastic-approximation-update">damped σ step</a> instead of assigning a single draw’s maximiser (issue #1445), so the collapse it guarded against no longer happens on a <code>combined()</code> model whose additive term is identified. The warning remains, because an additive term that genuinely is <em>not</em> identified in the data will still land on the bound and you should see that: check it yourself (RSE, σ-correlation, profile likelihood), and on sparse data prefer the importance-sampling −2LL over the Laplace OFV when judging whether the additive term is real.</li>
<li><strong>FOCE OFV</strong>: Compute the objective function using the FOCE/Laplace approximation, so AIC and BIC are directly comparable with FOCE results</li>
<li><strong>Covariance Step</strong>: Optionally compute standard errors via finite-difference Hessian (same method as FOCE)</li>
<li><strong>Diagnostics</strong>: Compute PRED, IPRED, CWRES, IWRES for each subject</li>
</ol>
<p>For sparsely-sampled data where the Laplace OFV is biased, you can append an importance-sampling stage that estimates <code>−2 log L</code> by Monte Carlo:</p>
<pre><code>method = [saem, imp]</code></pre>
<p>See <a href="../estimation/importance-sampling.html">Importance Sampling (IMP)</a>.</p>
</section>
<section id="conditional-distribution-conditional-mode-vs.-distribution" class="level2">
<h2 class="anchored" data-anchor-id="conditional-distribution-conditional-mode-vs.-distribution">Conditional Distribution (conditional mode vs.&nbsp;distribution)</h2>
<p>The post-SAEM finalization above produces the conditional <strong>mode</strong> of each subject’s random effects — the empirical Bayes estimate (EBE), the single most probable \( _i \). That is a point estimate. SAEM’s MCMC E-step is, however, already sampling each subject’s full <strong>conditional distribution</strong> \( p(_i y_i; ) \); the mode discards everything but its peak.</p>
<p>Set <code>conddist = true</code> to run an opt-in post-fit pass that characterises that distribution. With the population parameters fixed at their converged values, the same MH kernels (block, componentwise, and the per-occasion kappa kernel for IOV) are re-run per subject — warm-started at the EBE mode — and the draws are <em>accumulated</em> rather than discarded. The pass reports, per subject:</p>
<ul>
<li>the <strong>conditional mean</strong> \( [_i y_i] \),</li>
<li>the <strong>conditional SD</strong> \( (_i y_i) \),</li>
<li>optionally the raw draws (<code>conddist_keep_samples = true</code>), and</li>
<li>a distribution-based <strong>η-shrinkage</strong>, \( 1 - _i(_i)/\), reported alongside the usual mode-based <code>shrinkage_eta</code>.</li>
</ul>
<p>This mirrors the conditional-mode vs.&nbsp;conditional-distribution distinction in <strong>saemix</strong> (<code>map.saemix</code> vs <code>conddist.saemix</code>; Comets, Lavenu &amp; Lavielle, <em>J. Stat. Soft.</em> 80(3), 2017) and <strong>Monolix</strong> (the “Conditional Mode” vs “Conditional Distribution” tasks). Why prefer the distribution for diagnostics: EBEs and conditional means are shrunk toward the population, so η–covariate and η–η relationships built on them can be hidden or fabricated; samples from the conditional distribution are not shrinkage-biased.</p>
<p>Results are exposed on <code>FitResult.cond_dist</code> and written by the CLI to <code>{model}-conddist.csv</code> (<code>ID, ETA, COND_MEAN, COND_SD, COND_MODE</code>), with the raw draws in <code>{model}-conddist-samples.csv</code> when retained.</p>
<section id="validation-against-saemix-and-nonmem" class="level3">
<h3 class="anchored" data-anchor-id="validation-against-saemix-and-nonmem">Validation against saemix and NONMEM</h3>
<p>On the bundled warfarin data (10 subjects, 1-cpt oral, log-normal CL/V/KA, proportional error), all three engines converge to identical population parameters (TVCL 0.1327, TVV 7.737, TVKA 0.811), and ferx’s per-subject conditional distribution agrees with both references to within Monte-Carlo noise.</p>
<p><strong>vs saemix</strong> (<code>conddist.saemix</code>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity (per-subject η)</th>
<th>corr</th>
<th>max|diff|</th>
<th>RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>conditional mean</td>
<td>1.0000</td>
<td>0.0029</td>
<td>0.0011</td>
</tr>
<tr class="even">
<td>conditional SD</td>
<td>0.9913</td>
<td>0.0024</td>
<td>0.0009</td>
</tr>
<tr class="odd">
<td>mode / MAP</td>
<td>1.0000</td>
<td>0.0002</td>
<td>0.0001</td>
</tr>
</tbody>
</table>
<p><strong>vs NONMEM</strong> (<code>$EST METHOD=SAEM</code> then <code>METHOD=IMP EONLY=1</code>; conditional moments read from the <code>.phi</code> file — <code>PHI(k) − log θ_k</code> is the η conditional mean, <code>sqrt(PHC(k,k))</code> the conditional SD):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity (per-subject η)</th>
<th>corr</th>
<th>max|diff|</th>
<th>RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>conditional mean</td>
<td>1.0000</td>
<td>0.0012</td>
<td>0.0004</td>
</tr>
<tr class="even">
<td>conditional SD</td>
<td>0.9987</td>
<td>0.0017</td>
<td>0.0004</td>
</tr>
</tbody>
</table>
<p>(ferx <code>conddist_nsamp = 2000</code>. Comparison scripts: <code>tests/reference/saem_conddist/bench_saemix_conddist.R</code>, <code>tests/reference/saem_conddist/parse_nm_conddist.R</code>.)</p>
</section>
<section id="validation-of-the-logit-closed-form-m-step-918" class="level3">
<h3 class="anchored" data-anchor-id="validation-of-the-logit-closed-form-m-step-918">Validation of the logit closed-form M-step (#918)</h3>
<p>Parallel dual first-order absorption (fast <code>KA1</code> / slow <code>KA2</code>) with the pathway fraction carrying logit-scale IIV — <code>FR1 = 1/(1 + exp(-(LOGIT_FR1 + ETA_FR1)))</code>. 60 subjects × 16 samples, simulated from the model itself (<code>nonmem_anchor/simulate_logit_fraction_data.py</code>); the NONMEM side writes the same relationship with explicit mu syntax (<code>MU_3 = THETA(3)</code>, <code>nonmem_anchor/logit_fraction_saem.ctl</code>, <code>METHOD=SAEM</code>). Both start at <code>FR1 = 0.4</code>, the mirror image of the truth.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">truth</th>
<th style="text-align: right;">ferx SAEM (before #918)</th>
<th style="text-align: right;">ferx SAEM</th>
<th style="text-align: right;">NONMEM SAEM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>LOGIT_FR1</code></td>
<td style="text-align: right;">0.4055</td>
<td style="text-align: right;">0.2462</td>
<td style="text-align: right;">0.3793</td>
<td style="text-align: right;">0.4219</td>
</tr>
<tr class="even">
<td><code>FR1</code> = <code>inv_logit(LOGIT_FR1)</code></td>
<td style="text-align: right;">0.600</td>
<td style="text-align: right;">0.561</td>
<td style="text-align: right;">0.594</td>
<td style="text-align: right;">0.604</td>
</tr>
<tr class="odd">
<td><code>ω²(ETA_FR1)</code> (logit scale)</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.183</td>
</tr>
<tr class="even">
<td><code>CL</code></td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">5.35</td>
<td style="text-align: right;">5.31</td>
<td style="text-align: right;">5.29</td>
</tr>
<tr class="odd">
<td><code>V</code></td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">51.4</td>
<td style="text-align: right;">54.6</td>
<td style="text-align: right;">55.7</td>
</tr>
</tbody>
</table>
<p>Before the fix the fraction’s typical value went through the numeric M-step and stalled short of the truth, with <code>ω²(ETA_FR1)</code> inflating to absorb the bias — the same θ / η-mean confounding the closed-form step exists to remove. The slow-gated <code>tests/saem_logit_mu_ref.rs</code> pins the comparison.</p>
</section>
<section id="validation-of-the-covariate-mu-reference-m-step-619" class="level3">
<h3 class="anchored" data-anchor-id="validation-of-the-covariate-mu-reference-m-step-619">Validation of the covariate mu-reference M-step (#619)</h3>
<p>Two matched fixtures, 60 subjects × 7 samples each, simulated from the model under test (<code>nonmem_anchor/simulate_covmuref_data.py</code>; covariates constant within each subject, so the exact Gauss–Newton engine runs). The NONMEM side is <code>METHOD=SAEM</code> with the mu written out: the <em>nonlinear</em> <code>MU_1 = LOG(THETA(1) + (CRCL-90)*THETA(2))</code> for the additive renal gradient, the linear <code>MU_1 = LOG(THETA(1)) + THETA(2)*LOG(WT/70)</code> for the allometric exponent (<code>nonmem_anchor/covmuref_{additive,power}_saem.ctl</code>). Both engines start at the same values, deliberately away from the truth.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">truth</th>
<th style="text-align: right;">start</th>
<th style="text-align: right;">ferx SAEM (before #619)</th>
<th style="text-align: right;">ferx SAEM</th>
<th style="text-align: right;">NONMEM SAEM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>additive:</strong> <code>TVCL</code></td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">3.990</td>
<td style="text-align: right;">4.921</td>
<td style="text-align: right;">4.917</td>
</tr>
<tr class="even">
<td><code>TH_CRCL</code></td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;"><strong>0.0198</strong></td>
<td style="text-align: right;">0.04179</td>
<td style="text-align: right;">0.04178</td>
</tr>
<tr class="odd">
<td><code>TVV</code></td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">48.09</td>
<td style="text-align: right;">48.09</td>
<td style="text-align: right;">48.09</td>
</tr>
<tr class="even">
<td><code>ω²(ETA_CL)</code></td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: right;">0.0403</td>
<td style="text-align: right;">0.0401</td>
</tr>
<tr class="odd">
<td><code>ω²(ETA_V)</code></td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.0360</td>
<td style="text-align: right;">0.0358</td>
<td style="text-align: right;">0.0360</td>
</tr>
<tr class="even">
<td><strong>power:</strong> <code>TVCL</code></td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">4.919</td>
<td style="text-align: right;">4.787</td>
<td style="text-align: right;">4.788</td>
</tr>
<tr class="odd">
<td><code>TH_WT</code></td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;"><strong>0.332</strong></td>
<td style="text-align: right;">0.9221</td>
<td style="text-align: right;">0.9213</td>
</tr>
<tr class="even">
<td><code>TVV</code></td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">49.51</td>
<td style="text-align: right;">49.50</td>
<td style="text-align: right;">49.52</td>
</tr>
<tr class="odd">
<td><code>ω²(ETA_CL)</code></td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.0975</td>
<td style="text-align: right;">0.0701</td>
<td style="text-align: right;">0.0697</td>
</tr>
<tr class="even">
<td><code>ω²(ETA_V)</code></td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.0459</td>
<td style="text-align: right;">0.0460</td>
<td style="text-align: right;">0.0459</td>
</tr>
</tbody>
</table>
<p>Before #619 the covariate theta never left its start in either shape — the eta-frozen numerical M-step has no leverage on it once the sampled η have absorbed the covariate structure, and the <code>TVCL</code>/<code>TH_CRCL</code> pair reported a correlation of 1.00 with RSEs in the tens of thousands of percent. With the group step ferx and NONMEM agree to three or four figures on every parameter (<code>TH_CRCL</code> to 8e-6), including the shape NONMEM handles most efficiently. <code>tests/saem_covariate_mu_ref.rs</code> (slow-gated) pins both comparisons and an IMP twin.</p>
<p>The <strong>time-varying</strong> engine has no NONMEM SAEM comparator (NONMEM’s MU must be constant within a subject). On the fluconazole model that motivated #619 (<code>CL = (TVCL_NR + (CKDCRCYS-90)*THETA_CLCKD) * exp(ETA_CL)</code>, CKDCRCYS changing within 27 of 31 subjects, SAEM seed 123) the renal gradient moves from a frozen 1.96 (start 2.0) to 1.18 and <code>TVCL_NR</code> from 153.9 (start 150) to 109.0, against NONMEM FOCE’s 1.41 and 122; the remaining distance to NONMEM’s OFV on that dataset predates this change and is tracked with the FOCEI comparison of the same model.</p>
</section>
<section id="validation-of-the-joint-m-step-for-a-shared-theta-1620" class="level3">
<h3 class="anchored" data-anchor-id="validation-of-the-joint-m-step-for-a-shared-theta-1620">Validation of the joint M-step for a shared theta (#1620)</h3>
<p><code>examples/two_cpt_oral_cov.ferx</code> on its bundled data, where <code>CL</code> and <code>V1</code> both read <code>THETA_WT</code>. The NONMEM side writes both mu’s linear in the shared <code>THETA(6)</code> (<code>nonmem_anchor/covmuref_shared_{saem,impmap}.ctl</code>, NONMEM 7.6.0); both engines start from the bundled model’s values. SAEM is seed 1 at 150/250 iterations.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">ferx SAEM (before #1620)</th>
<th style="text-align: right;">ferx SAEM</th>
<th style="text-align: right;">NONMEM SAEM</th>
<th style="text-align: right;">ferx IMPMAP (before)</th>
<th style="text-align: right;">ferx IMPMAP</th>
<th style="text-align: right;">NONMEM IMPMAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>THETA_WT</code></td>
<td style="text-align: right;"><strong>0.0101</strong></td>
<td style="text-align: right;">0.6479</td>
<td style="text-align: right;">0.6618</td>
<td style="text-align: right;">0.5684</td>
<td style="text-align: right;">0.6725</td>
<td style="text-align: right;">0.6621</td>
</tr>
<tr class="even">
<td><code>THETA_CRCL</code></td>
<td style="text-align: right;">0.6454</td>
<td style="text-align: right;">0.5663</td>
<td style="text-align: right;">0.5645</td>
<td style="text-align: right;"><strong>0.3581</strong></td>
<td style="text-align: right;">0.5622</td>
<td style="text-align: right;">0.5630</td>
</tr>
<tr class="odd">
<td><code>TVCL</code></td>
<td style="text-align: right;">4.972</td>
<td style="text-align: right;">4.940</td>
<td style="text-align: right;">4.940</td>
<td style="text-align: right;"><strong>4.744</strong></td>
<td style="text-align: right;">4.939</td>
<td style="text-align: right;">4.940</td>
</tr>
</tbody>
</table>
<p>Before #1620 the second mu-reference was declined and the first one’s M-step moved <code>THETA_WT</code> with <code>ETA_V1</code> left as drawn, so <code>φ_V1</code> absorbed V1’s half of every move: SAEM drove the exponent to its 0.01 lower bound at seed 1, under <code>score_sa</code> and at 300/700 (seeds 2 and 3 stopped at 0.096 and 0.239), and IMPMAP pulled the renal exponent down with it. Seeds 2 and 3 now give <code>THETA_WT</code> 0.627 and 0.662, the 300/700 schedule 0.672 and <code>mstep_solver = score_sa</code> 0.648. Models whose mu-references share no theta are bit-identical to before. ferx IMPMAP’s variance components on this model sit away from NONMEM’s whether or not a theta is shared (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1629">#1629</a>), so the table compares the joint group’s own coordinates. <code>tests/saem_covariate_mu_ref.rs</code> (slow-gated) pins the table’s two “after” columns and the <code>score_sa</code> and 300/700 runs against NONMEM; seeds 2 and 3 are reported here, not tested.</p>
</section>
</section>
<section id="inter-occasion-variability-iov" class="level2">
<h2 class="anchored" data-anchor-id="inter-occasion-variability-iov">Inter-Occasion Variability (IOV)</h2>
<p><code>method = saem</code> supports models with <code>kappa</code> declarations (<code>n_kappa &gt; 0</code>). IOV is handled with a per-occasion Gibbs Metropolis-Hastings step interleaved with the standard eta MH:</p>
<ul>
<li><strong>E-step</strong>: After sampling <span class="math inline">\(\eta\)</span>, one MH proposal is made for each occasion’s <span class="math inline">\(\kappa_k\)</span>. Both the eta and kappa samplers target the correct conditional distributions: <span class="math inline">\(p(\eta | \kappa, \theta, \text{data})\)</span> and <span class="math inline">\(p(\kappa_k | \eta, \theta, \text{data})\)</span> respectively.</li>
<li><strong>SA update</strong>: <span class="math inline">\(S_2^{\text{iov}} \leftarrow (1 - \gamma_k) S_2^{\text{iov}} + \gamma_k \cdot \frac{1}{N_{\text{occ}}} \sum_i \sum_k \kappa_{ik} \kappa_{ik}^T\)</span></li>
<li><strong>M-step</strong>: <span class="math inline">\(\Omega_{\text{iov}} = S_2^{\text{iov}}\)</span> (analytic update, same structure as the BSV omega M-step).</li>
</ul>
<p>No additional configuration is required; <code>method = saem</code> works for both BSV-only and IOV models.</p>
</section>
<section id="models-with-no-random-effects-are-rejected" class="level2">
<h2 class="anchored" data-anchor-id="models-with-no-random-effects-are-rejected">Models with no random effects are rejected</h2>
<p>SAEM is an EM algorithm <em>over the random effects</em>. A model that declares none (<code>n_eta = 0</code> — see <a href="../model-file/parameters.html#no-omega-at-all-fixed-effects-only-naive-pooled-fits">no omega at all</a>) has an empty E-step: there is nothing to sample and the stochastic approximation has nothing to average, leaving an M-step that is plain maximum likelihood on θ/σ. Left to run, it terminates on its own criterion slightly short of the optimum — on the <code>one_cpt_iv</code> zero-Ω anchor it reports converged at OFV −269.599 where FOCEI reaches −269.637.</p>
<p>Rather than return a quietly-wrong answer, <code>method = saem</code> errors at <code>n_eta = 0</code>:</p>
<pre class="text"><code>method = saem requires at least one random effect (n_eta = 0). SAEM is an EM over
the random effects, so with none declared its E-step is empty and it only
approaches the objective that FOCE/FOCEI minimise exactly. Use method = foce,
focei, or laplace for a fixed-effects-only (naive-pooled) model.</code></pre>
<p>The check runs in the same validation pass as <code>ferx check</code>, and fires if <code>saem</code> appears <strong>anywhere</strong> in a <code>methods = [...]</code> chain — so <code>methods = [saem, focei]</code> fails up front rather than after the SAEM stage has already run.</p>
<p><code>imp</code>, <code>impmap</code> and <code>bayes</code> are rejected at <code>n_eta = 0</code> in the same pass, under the code <code>E_METHOD_NO_RANDOM_EFFECTS</code> (#1007) — each integrates over the random effects, and with none declared the marginal likelihood collapses to the observation likelihood FOCE/FOCEI already minimise exactly. Like the SAEM guard this fires anywhere in a chain, so <code>methods = [focei, imp]</code> fails up front instead of after the FOCEI stage has run. Each of the three still refuses at run time as well, which is what a direct <code>fit()</code> caller bypassing <code>ferx check</code> sees.</p>
</section>
<section id="configuration" class="level2">
<h2 class="anchored" data-anchor-id="configuration">Configuration</h2>
<pre><code>[fit_options]
  method        = saem
  n_exploration = 150      # Phase 1 iterations
  n_convergence = 250      # Phase 2 iterations
  n_mh_steps    = auto     # block-MH steps/subject/iteration, or `auto` (see above)
  n_leapfrog    = 0        # Set &gt; 0 (e.g. 3) to use HMC instead of MH
  adapt_interval = 50      # Step-size adaptation frequency (interval rule)
  scale_adaptation = interval  # or robbins_monro
  omega_burnin  = 20       # Iterations to hold Ω fixed while the chain warms up
  seed          = 12345    # RNG seed for reproducibility
  covariance    = true     # Compute standard errors

  # Conditional-distribution pass (opt-in; off by default)
  conddist              = true    # Estimate p(η_i | y_i) per subject after the fit
  conddist_nsamp        = 2000    # Retained MCMC draws per subject
  conddist_burnin       = 500     # Burn-in draws discarded before accumulation
  conddist_keep_samples = false   # Retain the raw draws (writes -conddist-samples.csv)</code></pre>
</section>
<section id="tuning-guide" class="level2">
<h2 class="anchored" data-anchor-id="tuning-guide">Tuning Guide</h2>
<section id="not-converging" class="level3">
<h3 class="anchored" data-anchor-id="not-converging">Not Converging</h3>
<ul>
<li>Increase <code>n_exploration</code> (e.g., 300) to give more time for basin finding</li>
<li>Increase <code>n_convergence</code> (e.g., 500) for a longer averaging window</li>
<li>Raise <code>n_mh_steps</code> above what <code>auto</code> resolves to (e.g.&nbsp;30-50) for better mixing in the E-step on hard surfaces. The rule caps at 20, the count calibrated to escape the basin trap observed on Emax PKPD with stressful initial values (see below), and it reaches that cap only at 8 observations per subject per η; an ODE-with-Form-C readout may need more proposals than either to fully decorrelate samples between M-step calls.</li>
</ul>
</section>
<section id="pd-curve-thetas-collapse-on-cold-start-emax-sigmoid-readouts" class="level3">
<h3 class="anchored" data-anchor-id="pd-curve-thetas-collapse-on-cold-start-emax-sigmoid-readouts">PD-curve thetas collapse on cold start (Emax / sigmoid readouts)</h3>
<p>A failure mode specific to models that read population thetas through a Form C <code>[scaling]</code> block (e.g.&nbsp;<code>y[CMT=N] = E0 + EMAX * effect^GAMMA / ...</code>) and score them via a per-CMT additive <code>[error_model]</code>: from stressful initial values (e.g.&nbsp;1.5× truth) the M-step can lock the PD-curve thetas into a degenerate basin where <code>E0 → 0</code>, <code>EMAX</code> and <code>EC50</code> blow up, and <code>GAMMA</code> collapses below 1. The likelihood at the bad basin is only modestly worse than at truth (~150 OFV units on a 100-subject benchmark), so SAEM doesn’t back out on its own.</p>
<p>The underlying cause is MCMC sample correlation: with an early default <code>n_mh_steps = 3</code> the chain didn’t decorrelate enough between SAEM outer iterations, so the single-draw stochastic M-step received sticky correlated ETAs that biased the population-θ update toward the basin. The default was raised to 10 and then to 20 (alongside the componentwise kernel and the damped Ω step), which resolves this reliably across seeds at modest extra wall on the affected model and ~0% on simpler PK-only models.</p>
<p>This benchmark has 16 observations per subject against 2 η, so the <code>auto</code> rule resolves it to the same 20: <strong>the count that closed this trap is unchanged on the model it was calibrated on</strong> (#1459). Re-measuring it on <code>e7343462</code> at 6 seeds, the boundary collapse itself no longer reproduces at any count from 2 to 20 — <code>E0</code> lands at 1.83–2.02 against a truth of 2 and <code>GAMMA</code> at 0.89–1.08, never at a bound — but what 20 still buys is reproducibility along the EMAX/EC50 ridge: final-estimate distance 0.029 and cross-seed stability 0.044 at 20, against 0.076–0.173 and 0.090–0.160 at 4–8. That ridge is a property of the data, not of the sampler (FOCEI on the same dataset lands at EMAX 20.0 / EC50 1.78 where SAEM lands at 53.1 / 7.28), so report both endpoints and check several seeds on any Emax/Hill fit.</p>
<p>If you still see this signature (E0 hitting its lower bound, EMAX large, EC50 large) on a related Emax/Hill model:</p>
<ol type="1">
<li>Try <code>n_mh_steps = 50</code> (above the <code>auto</code> cap of 20)</li>
<li>Warm-start from a FOCEI fit (<code>method = [focei, saem]</code>)</li>
<li>Run with several seeds and keep the lowest OFV</li>
</ol>
</section>
<section id="ω-collapses-residual-error-inflates" class="level3">
<h3 class="anchored" data-anchor-id="ω-collapses-residual-error-inflates">Ω Collapses / Residual Error Inflates</h3>
<p>On sparse data (few observations per subject) the variance components can collapse toward zero on the first iterations while the residual error absorbs the between-subject variability (e.g.&nbsp;tiny <code>omega</code> with a large additive <code>sigma</code>). The default <code>omega_burnin = 20</code> and the damped Ω SA step guard against this by keeping Ω near its starting value while the chain warms up. If it still occurs, raise <code>omega_burnin</code> (e.g.&nbsp;40) and/or <code>n_mh_steps</code> so the chain reaches a representative spread before Ω is first estimated, then polish with <code>method = [saem, focei]</code>.</p>
</section>
<section id="block-ω-correlations-near-1-rank-1-collapse" class="level3">
<h3 class="anchored" data-anchor-id="block-ω-correlations-near-1-rank-1-collapse">Block Ω correlations near ±1 (rank-1 collapse)</h3>
<p>For a <code>block_omega</code> (correlated) random-effects block, a faulty E-step/M-step coupling can drive <strong>every</strong> off-diagonal correlation toward ±1 while one variance collapses toward zero — a near rank-1 Ω that FOCEI on the same data does not show. The mechanism is the block proposal (preconditioned by <code>chol(Ω)</code>) plus the single-draw Ω M-step feeding correlation back into Ω during the <code>γ=1</code> exploration phase. ferx guards this by default with two mechanisms — the <strong>componentwise MH kernel</strong> and the <strong>damped Ω SA step</strong> described above — so on a poorly-identified 2-cpt model the SAEM Ω now matches the FOCEI/NONMEM estimate (e.g.&nbsp;corr(CL,V1) ≈ 0.67, corr(V1,V2) ≈ 0.4) across seeds instead of collapsing to ≈0.99. If you still see inflated block correlations, raise <code>n_mh_steps</code> (this also raises the componentwise sweep count <code>n_mh_steps / n_eta</code>) and run several seeds.</p>
</section>
<section id="the-additive-term-of-a-combined-error-model" class="level3">
<h3 class="anchored" data-anchor-id="the-additive-term-of-a-combined-error-model">The additive term of a <code>combined()</code> error model</h3>
<p>Before ferx #1445 the additive component of <code>combined(PROP, ADD)</code> could be driven onto its optimizer lower bound on sparse data where NONMEM’s own SAEM estimates a clearly non-zero value, and it got <em>worse</em> with more iterations. The cause was the σ half of the numerical M-step being assigned outright rather than averaged: the additive term of a combined model is often a <strong>minority</strong> variance component, identified only where <span class="math inline">\(\sigma_{\text{add}}\)</span> and <span class="math inline">\(\sigma_{\text{prop}}\cdot f\)</span> are comparable, and the conditional maximiser of a weakly identified variance component from a single η draw sits near zero a large fraction of the time. The <a href="#stochastic-approximation-update">damped σ step</a> makes the estimate the average of that sequence rather than its last draw.</p>
<p>Anchored against NONMEM 7.5.1 <code>METHOD=SAEM</code> on the same 300-subject, median-one-observation dataset (<code>nonmem_anchor/saem_sparse_combined_saem.ctl</code> and <code>data/saem_sparse_combined.csv</code>, which is the fixture <code>tests/saem_combined_error.rs</code> scores; results in <code>nonmem_anchor/results/saem_sparse_combined_saem.ext</code>, read from the <code>.ext</code> because a SAEM+IMP chain truncates its <code>.lst</code>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>additive SD (truth 1.8)</th>
<th>proportional SD (truth 0.13)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NONMEM SAEM, <code>ISAMPLE=10</code></td>
<td>1.5425</td>
<td>0.1370</td>
</tr>
<tr class="even">
<td>NONMEM SAEM, <code>ISAMPLE=2</code> (its default)</td>
<td>1.6463</td>
<td>0.1491</td>
</tr>
<tr class="odd">
<td>ferx SAEM <strong>after</strong> #1445, 8 seeds</td>
<td>1.42 [1.11, 1.75]</td>
<td>0.139</td>
</tr>
<tr class="even">
<td>ferx SAEM <strong>before</strong> #1445, 3 seeds</td>
<td>0.011 / 0.0025 / 0.011</td>
<td>0.135</td>
</tr>
<tr class="odd">
<td>ferx FOCEI</td>
<td>3.220</td>
<td>0.1200</td>
</tr>
</tbody>
</table>
<p>ferx SAEM now agrees with NONMEM SAEM on the additive term to 8% of the simulation truth and on the proportional term to 1.5%, where before it sat four orders of magnitude below it. (NONMEM’s <code>ISAMPLE=2</code> default collapses the two weakly identified Ω diagonals on this design — 8.8e-4 and 0.032 against truths 0.15 and 0.69 — which is why the <code>ISAMPLE=10</code> arm is the headline; the σ estimate moves only from 1.65 to 1.54 between them.) On a real dataset, <code>ferx-testdata/cefepime_jordan</code> run64, NONMEM FOCEI estimates the additive RUV at 1.550 (<code>nm/run64.ext</code>, THETA(6)); ferx SAEM reports 1.16 [0.97, 1.34] after the change and ~1e-3 before it.</p>
<p>Note what the objective does <strong>not</strong> say here: on the simulated fixture the importance-sampled −2 log L is 3183.1 after against 3183.4 before, a 0.2 difference that is pure noise. That is not a defect in the comparison, it is the whole problem restated — a minority variance component is weakly identified, the likelihood is nearly flat in it, and an estimator that reports a single draw of a flat direction will wander to the boundary while barely moving the objective. Rank the two by the parameter against a known truth and an external engine, not by the likelihood they are nearly tied on.</p>
<p>The price is that σ now <em>lags</em>: it is a Robbins-Monro average over the convergence phase, so a run that is too short reports a σ still on its way down from the starting guess. If σ has clearly not settled, lengthen the run (<code>n_exploration</code> first, so averaging starts from an equilibrated chain) rather than reading the last value. If <code>ADD</code> still lands on its bound, it is genuinely not identified by the data — check it (RSE, σ-correlation, profile likelihood) rather than assuming the estimator.</p>
</section>
<section id="iiv-on-residual-error-iiv_on_ruv-σ-ω_ruv-ridge" class="level3">
<h3 class="anchored" data-anchor-id="iiv-on-residual-error-iiv_on_ruv-σ-ω_ruv-ridge">IIV on residual error (<code>iiv_on_ruv</code>): σ × ω_RUV ridge</h3>
<p>With <code>iiv_on_ruv = ETA</code>, the residual is <span class="math inline">\(Y = f + \varepsilon \exp(\eta_{\text{RUV}})\)</span>, so the residual variance is <span class="math inline">\(\sigma^2 \exp(2\eta_{\text{RUV}})\)</span>. This form is invariant to <span class="math inline">\(\eta_{\text{RUV}} \to \eta_{\text{RUV}} - c,\ \sigma \to \sigma\,e^{c}\)</span> — <span class="math inline">\(\sigma\)</span> and a <em>shift</em> of <span class="math inline">\(\eta_{\text{RUV}}\)</span> are a degenerate pair. Unlike a mu-referenced structural <span class="math inline">\(\eta\)</span> (whose mean is folded into its typical value <span class="math inline">\(\theta\)</span> each M-step), <span class="math inline">\(\eta_{\text{RUV}}\)</span> has <strong>no typical-value <span class="math inline">\(\theta\)</span></strong>, so nothing absorbs its mean: it drifts along that degenerate direction, and because <span class="math inline">\(\omega_{\text{RUV}}\)</span> is estimated as <span class="math inline">\(\overline{\eta_{\text{RUV}}^2}\)</span> the drift injects a spurious <span class="math inline">\(\text{mean}^2\)</span> term that pumps <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\omega_{\text{RUV}}\)</span> <strong>up together</strong> — the runaway reported in issue #895 (<span class="math inline">\(\omega_{\text{RUV}}\)</span> toward ~49, <span class="math inline">\(\sigma\)</span> toward its e⁵ ceiling), worst on FREM models with an extreme <span class="math inline">\(\Omega\)</span>-diagonal scale range.</p>
<p>ferx fixes this by treating <span class="math inline">\(\sigma\)</span> as the residual-scale typical value: each iteration <span class="math inline">\(\eta_{\text{RUV}}\)</span> is <strong>re-centred to zero mean</strong>, absorbing the shift into <span class="math inline">\(\sigma\)</span> (<span class="math inline">\(\eta_{\text{RUV}} \mathrel{-}= \overline{\eta_{\text{RUV}}}\)</span>, every RUV-scaled <span class="math inline">\(\sigma \mathrel{\times}= e^{\overline{\eta_{\text{RUV}}}}\)</span>). Each subject’s residual variance is exactly unchanged, so the likelihood is untouched, but <span class="math inline">\(E[\eta_{\text{RUV}}]=0\)</span> is restored and <span class="math inline">\(\omega_{\text{RUV}}\)</span> measures the true variance. On the 475-subject FREM reprex this converges to <span class="math inline">\(\omega_{\text{RUV}} \approx 0.28\)</span>, <span class="math inline">\(\sigma \approx 0.20\)</span> from both a too-small and a too-large <span class="math inline">\(\sigma\)</span> start (NONMEM: 0.28 / 0.18), where it previously ran to <span class="math inline">\(\omega_{\text{RUV}} \approx 49\)</span>. Re-centring is applied only when <strong>every</strong> RUV-scaled <span class="math inline">\(\sigma\)</span> component is free to absorb the shift — this keeps each subject’s residual variance exactly unchanged. If any residual <span class="math inline">\(\sigma\)</span> component is FIXed (e.g.&nbsp;a fixed additive term of a combined error), scaling only the free component would leave the fixed part uncompensated, so re-centring is skipped and the growth caps below carry the load (a FIXed <span class="math inline">\(\sigma\)</span> already partially pins the mean).</p>
<p>Two growth caps remain as belt-and-braces backstops, both no-ops on a well-behaved fit:</p>
<ul>
<li><strong>σ growth cap</strong> — each free RUV-scaled residual <span class="math inline">\(\sigma\)</span> is capped at <span class="math inline">\(\approx 20\times\)</span> its scale (a post-M-step clamp). A <span class="math inline">\(\sigma\)</span> whose own user upper bound is already tighter carries no separate cap — NLopt enforces that bound directly.</li>
<li><strong>ω_RUV growth cap</strong> — the RUV <span class="math inline">\(\Omega\)</span> variance is capped at <span class="math inline">\(\approx 20\times\)</span> its scale, applied as a correlation-preserving rescale of the RUV row/column so a block <span class="math inline">\(\Omega\)</span> stays positive-definite. A FIXed off-diagonal covariance with the RUV eta is left exactly as declared.</li>
</ul>
<p>The reference “scale” is the <em>larger</em> of the starting value and the data-informed value the fit reaches by the end of the exploration phase, so a run started from a <span class="math inline">\(\sigma\)</span>/<span class="math inline">\(\omega_{\text{RUV}}\)</span> guess many-fold below the truth is not spuriously clamped. If either cap ever binds (it should not, now that the drift is removed), SAEM warns that the split is weakly identified and suggests fixing <span class="math inline">\(\sigma\)</span>.</p>
</section>
<section id="slow-convergence" class="level3">
<h3 class="anchored" data-anchor-id="slow-convergence">Slow Convergence</h3>
<ul>
<li>Decrease <code>n_exploration</code> and <code>n_convergence</code> if parameters stabilize early</li>
<li>Use <code>adapt_interval = 25</code> for faster step-size adaptation, or <code>scale_adaptation = robbins_monro</code> when the acceptance-rate warning says the scales never reached their target</li>
</ul>
</section>
<section id="reproducibility" class="level3">
<h3 class="anchored" data-anchor-id="reproducibility">Reproducibility</h3>
<ul>
<li>Always set <code>seed</code> for reproducible results</li>
<li>Different seeds will produce slightly different estimates due to the stochastic nature of the algorithm</li>
</ul>
</section>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">Output</h2>
<p>The SAEM iteration progress is printed to stderr:</p>
<pre><code>SAEM: 10 subjects, 3 ETAs, 400 total iter (150 explore + 250 converge)
  SAEM iter    1/400 [explore] γ=1.000  condNLL=95.244
  SAEM iter   50/400 [explore] γ=1.000  condNLL=56.705
  SAEM iter  150/400 [explore] γ=1.000  condNLL=46.071
  SAEM iter  200/400 [converge] γ=0.020  condNLL=36.799
  SAEM iter  400/400 [converge] γ=0.004  condNLL=38.096
SAEM iterations complete. Computing final EBEs and OFV...
SAEM completed. Final OFV = ...
Running covariance step...</code></pre>
<p>The <code>Final OFV = ...</code> line is printed <strong>before</strong> the covariance step starts (#893). SAEM only learns its OFV at the very end (the final FOCE approximation), and the covariance matrix is often the most expensive part of the run — so seeing the OFV first lets you interrupt (Ctrl-C) when the OFV already rules the run out, instead of waiting for a covariance matrix you won’t use.</p>
<section id="why-γ-gamma-is-shown" class="level3">
<h3 class="anchored" data-anchor-id="why-γ-gamma-is-shown">Why <code>γ</code> (gamma) is shown</h3>
<p><span class="math inline">\(\gamma_k\)</span> is the <strong>stochastic-approximation step size</strong>, not a model quantity — it is intrinsic to the SAEM algorithm and tells you which phase the run is in and how aggressively the estimates are still moving:</p>
<ul>
<li><strong>Exploration</strong> (<code>[explore]</code>, <span class="math inline">\(k \le K_1\)</span>): <span class="math inline">\(\gamma_k = 1\)</span>. Each iteration fully replaces the running sufficient statistics, so the chain roams freely toward the basin of the MLE.</li>
<li><strong>Convergence</strong> (<code>[converge]</code>, <span class="math inline">\(k &gt; K_1\)</span>): <span class="math inline">\(\gamma_k = 1/(k - K_1)\)</span> decays toward zero. Updates shrink into a decreasing-weight average that damps the Monte-Carlo noise so the estimates settle. The printed value (e.g.&nbsp;<code>0.020</code>, <code>0.004</code>) is exactly this decaying weight applied to the Ω, θ, and σ updates each iteration.</li>
</ul>
</section>
<section id="why-condnll-and-not-ofv" class="level3">
<h3 class="anchored" data-anchor-id="why-condnll-and-not-ofv">Why <code>condNLL</code> and not <code>OFV</code></h3>
<p>During the iterations ferx prints <code>condNLL</code>, the <strong>conditional</strong> (joint) negative log-likelihood summed over subjects, evaluated at the <em>current MH/HMC-sampled</em> etas:</p>
<p><span class="math display">\[
\text{condNLL} = \sum_{i=1}^{N} \text{NLL}(\eta_i^{\text{sampled}})
\]</span></p>
<p>This is a cheap per-iteration progress signal. It is <strong>not</strong> the marginal objective function value (OFV): it is evaluated at one stochastic draw of the random effects rather than integrated over their distribution, so unlike the FOCE/FOCEI outer-loop OFV it is noisy, will not decrease monotonically, and is <strong>not comparable across runs</strong> for model selection.</p>
<p>The true marginal <strong>OFV</strong> (<span class="math inline">\(-2 \log L\)</span> via the Laplace approximation, directly comparable with FOCE for AIC/BIC) is expensive and is therefore computed only once, after the iterations finish — this is the <code>Final OFV = ...</code> line. See <a href="#post-saem-finalization">Post-SAEM Finalization</a>.</p>
<p>(<code>NLL</code> = <em>negative log-likelihood</em>, i.e.&nbsp;<span class="math inline">\(-\log L\)</span>. NONMEM’s <code>OFV = -2 \log L</code> is essentially <code>2 × NLL</code> plus a constant.)</p>
<p><code>condNLL</code> should generally decrease during the exploration phase and stabilize during convergence.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script>
(function () {
  var HEAD = '<div class="panel-head"><span class="dots"><i></i><i></i><i></i></span><span class="file"><span class="br">[</span>warfarin_pk.ferx<span class="br">]</span></span></div>';

  function apply() {
    var dark = document.documentElement.getAttribute('data-bs-theme') === 'dark';
    document.querySelectorAll('div.sourceCode').forEach(function (el) {
      if (el.parentElement && el.parentElement.closest('.code-panel')) return;
      if (dark) {
        if (!el.classList.contains('code-panel')) {
          el.classList.add('code-panel');
          el.insertAdjacentHTML('afterbegin', HEAD);
        }
      } else {
        el.classList.remove('code-panel');
        var h = el.querySelector(':scope > .panel-head');
        if (h) h.remove();
      }
    });
  }

  if (document.body) apply();
  document.addEventListener('DOMContentLoaded', apply);
  new MutationObserver(function (ms) {
    ms.forEach(function (m) { if (m.attributeName === 'data-bs-theme') apply(); });
  }).observe(document.documentElement, { attributes: true });
}());
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ferx-nlme\.org\/ferx-core\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 FeRx-NLME · MIT licensed</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FeRx-NLME/ferx-core/edit/main/estimation/saem.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-core/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Fe · 26 · Rx · 2026</p>
</div>
  </div>
</footer>




</body></html>