<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Estimate nonlinear mixed-effects parameter uncertainty with Sampling Importance Resampling in ferx.">

<title>Sampling Importance Resampling (SIR) – ferx-core</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/ferx-favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1a6b8152d35ce99ad89fbf7beccf1728.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-a739b0675e4828d39130ef8f9cb3f71b.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1a6b8152d35ce99ad89fbf7beccf1728.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-112e5622ee747e1c4dc4e363d1626892.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-570b18dfac9eba3e29c33095147666fc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-112e5622ee747e1c4dc4e363d1626892.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Sampling Importance Resampling (SIR)">
<meta property="og:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD and pharmacometrics">
<meta property="og:site_name" content="ferx-core">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="Sampling Importance Resampling (SIR)">
<meta name="twitter:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD and pharmacometrics">
<meta name="twitter:card" content="summary">
<link rel="canonical" href="https://ferx-nlme.org/ferx-core/estimation/sir.html">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://ferx-nlme.org/" class="navbar-brand navbar-brand-logo">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo light-content">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="https://ferx-nlme.org/">
    <span class="navbar-title">ferx-core</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/get-started.html"> 
<span class="menu-text">Get started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/design.html"> 
<span class="menu-text">Design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/features.html"> 
<span class="menu-text">Features</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/changelog.html"> 
<span class="menu-text">Changelog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/roadmap.html"> 
<span class="menu-text">Roadmap</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/blog/"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/ferx-core/"> 
<span class="menu-text">ferx-core</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/ferx-book/"> 
<span class="menu-text">ferx-r</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.org/reference/"> 
<span class="menu-text">Reference</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/FeRx-NLME"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../estimation/index.html">Estimation Methods</a></li><li class="breadcrumb-item"><a href="../estimation/sir.html">Sampling Importance Resampling (SIR)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../assets/ferx-favicon.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../maturity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Feature Maturity</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../installation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../quick-start.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quick Start</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../model-file/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model File Reference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/iov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-Occasion Variability (IOV)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/individual-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Individual Parameters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariate-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/structural-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/lagtime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lagtime</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/steady-state.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Steady-State Doses (SS=1)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/error-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Error Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/bloq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LOQ-Censored Observations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/ode-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/absorption.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Built-in Absorption Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/initial-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Initial Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/diffusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stochastic Differential Equations (SDE / Diffusion)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/covariate-nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>[covariate_nn]</code> — Deep Compartment Models (DCM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/data-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/derived.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Derived Columns (<code>[derived]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Output Columns (<code>[output]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/fit-options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fit Options</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/adaptive-dosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adaptive (Feedback) Dosing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/event-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-to-Event Endpoints (<code>[event_model]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical endpoints — <code>[binary_model]</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../model-file/markov-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Markov models ([markov_model])</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../estimation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimation Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/foce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FOCE / FOCEI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/agq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AGQ — Adaptive Gaussian Quadrature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/gauss-newton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gauss-Newton (BHHH)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/saem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SAEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/sir.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Sampling Importance Resampling (SIR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/importance-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importance Sampling (IMP)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/frem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FREM (Full Random Effects Model)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/impmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IMPMAP — Importance Sampling assisted by Mode A Posteriori</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayesian estimation (MCMC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/vi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variational Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/parameterization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Packed Parameter Space</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/optimizers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outer Optimizers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/tte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-to-Event (TTE) Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical endpoints (binary / logistic)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/ctmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous-time Markov models (CTMM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixture Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../estimation/priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parameter Priors (penalized ML / MAP)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tools/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tools</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/gam-screening.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GAM covariate screening</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Search configuration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/covsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/modelsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural model search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/ruvsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Residual-error search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/iivsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Variability-structure search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/iovsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-occasion variability search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/amd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Automatic model development</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tools/global-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Global model search</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data-format.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Format</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CLI Reference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Output Files</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../warnings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Warnings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../file-formats/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">File Formats</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../file-formats/fitrx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The <code>.fitrx</code> Fit Bundle</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../file-formats/check-report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Check Report (<code>ferx check --json</code>)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../examples/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Examples</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/one-cpt-oral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One-Compartment Oral (Warfarin)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/two-cpt-iv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two-Compartment IV Bolus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/covariates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariate Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/ode-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Model (Michaelis-Menten)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/bloq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BLOQ (M3 method)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/iov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inter-Occasion Variability (IOV)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/iov-saem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IOV with SAEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/multiple-dosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Dosing (ADDL Column)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/steady-state.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Steady-State Dosing (SS Column)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit Scaling (<code>[scaling]</code>)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/derived-output.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Derived Columns and Output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/data-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Selection (IGNORE / ACCEPT)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/ode-lagtime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ODE Model with Absorption Lag Time</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/transit-absorption.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transit Absorption (Two-Compartment)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/sde.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stochastic Differential Equations (SDE)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/frem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FREM (Covariate Analysis)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../examples/multistart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-Start: Michaelis-Menten Elimination</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../api/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rust API</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Core Types</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/parsing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../api/model-editing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model editing</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../development/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Development</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/contributing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributing to FeRx development</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/sdlc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Development Lifecycle (SDLC)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../development/docs-lint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Docs linter</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sampling-importance-resampling-sir" id="toc-sampling-importance-resampling-sir" class="nav-link active" data-scroll-target="#sampling-importance-resampling-sir">Sampling Importance Resampling (SIR)</a>
  <ul>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How It Works</a></li>
  <li><a href="#enabling-sir" id="toc-enabling-sir" class="nav-link" data-scroll-target="#enabling-sir">Enabling SIR</a></li>
  <li><a href="#options" id="toc-options" class="nav-link" data-scroll-target="#options">Options</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output">Output</a></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a>
  <ul class="collapse">
  <li><a href="#benchmark-warfarin-bundled-datawarfarin.csv-10-subjects" id="toc-benchmark-warfarin-bundled-datawarfarin.csv-10-subjects" class="nav-link" data-scroll-target="#benchmark-warfarin-bundled-datawarfarin.csv-10-subjects">Benchmark: warfarin (bundled <code>data/warfarin.csv</code>, 10 subjects)</a></li>
  <li><a href="#rank-deficient-and-non-identified-proposals" id="toc-rank-deficient-and-non-identified-proposals" class="nav-link" data-scroll-target="#rank-deficient-and-non-identified-proposals">Rank-deficient and non-identified proposals</a></li>
  <li><a href="#when-the-ess-is-below-100" id="toc-when-the-ess-is-below-100" class="nav-link" data-scroll-target="#when-the-ess-is-below-100">When the ESS is below 100</a>
  <ul class="collapse">
  <li><a href="#variances-the-data-do-not-bound-away-from-zero" id="toc-variances-the-data-do-not-bound-away-from-zero" class="nav-link" data-scroll-target="#variances-the-data-do-not-bound-away-from-zero">Variances the data do not bound away from zero</a></li>
  </ul></li>
  <li><a href="#choosing-the-target-scale" id="toc-choosing-the-target-scale" class="nav-link" data-scroll-target="#choosing-the-target-scale">Choosing the target scale</a></li>
  </ul></li>
  <li><a href="#computational-cost" id="toc-computational-cost" class="nav-link" data-scroll-target="#computational-cost">Computational Cost</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#running-sir-after-a-fit-run_sir" id="toc-running-sir-after-a-fit-run_sir" class="nav-link" data-scroll-target="#running-sir-after-a-fit-run_sir">Running SIR after a fit (<code>run_sir</code>)</a>
  <ul class="collapse">
  <li><a href="#which-settings-run_sir-uses" id="toc-which-settings-run_sir-uses" class="nav-link" data-scroll-target="#which-settings-run_sir-uses">Which settings <code>run_sir</code> uses</a></li>
  <li><a href="#which-objective-weights-the-draws" id="toc-which-objective-weights-the-draws" class="nav-link" data-scroll-target="#which-objective-weights-the-draws">Which objective weights the draws</a></li>
  <li><a href="#caller-supplied-vs.-re-read-inputs" id="toc-caller-supplied-vs.-re-read-inputs" class="nav-link" data-scroll-target="#caller-supplied-vs.-re-read-inputs">Caller-supplied vs.&nbsp;re-read inputs</a></li>
  <li><a href="#the-population-the-fit-was-given" id="toc-the-population-the-fit-was-given" class="nav-link" data-scroll-target="#the-population-the-fit-was-given">The population the fit was given</a></li>
  <li><a href="#hash-storage-on-fitresult" id="toc-hash-storage-on-fitresult" class="nav-link" data-scroll-target="#hash-storage-on-fitresult">Hash storage on <code>FitResult</code></a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/FeRx-NLME/ferx-core/edit/main/estimation/sir.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-core/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../estimation/index.html">Estimation Methods</a></li><li class="breadcrumb-item"><a href="../estimation/sir.html">Sampling Importance Resampling (SIR)</a></li></ol></nav></header>





<section id="sampling-importance-resampling-sir" class="level1">
<h1>Sampling Importance Resampling (SIR)</h1>
<blockquote class="blockquote">
<p><strong>Maturity: beta</strong> — see <a href="../maturity.html">Feature Maturity</a> for what this means.</p>
</blockquote>
<p>SIR is an optional post-estimation step that provides non-parametric parameter uncertainty estimates. It produces 95% confidence intervals that are more robust than the asymptotic covariance matrix, particularly for models with:</p>
<ul>
<li>Non-normal parameter distributions</li>
<li>Boundary estimates (parameters near constraints)</li>
<li>Small datasets where asymptotic assumptions may not hold</li>
</ul>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How It Works</h2>
<p>SIR uses the maximum likelihood estimates and their covariance matrix as a proposal distribution, then reweights samples based on the actual likelihood:</p>
<ol type="1">
<li><strong>Sample</strong>: Draw M parameter vectors from a multivariate Student-t distribution (default ν=5) centered on the ML estimates, using the estimation covariance matrix as the scale</li>
<li><strong>Importance weighting</strong>: For each sample, compute the objective function value (OFV) and calculate an importance weight based on the ratio of the true likelihood to the proposal density</li>
<li><strong>Resample</strong>: Draw m vectors (with replacement) proportional to the importance weights</li>
</ol>
<p>The resampled vectors approximate the true parameter uncertainty distribution. Confidence intervals are derived from their empirical percentiles.</p>
<p>A probability-scale theta (<code>inv_logit(logit(THETA) + ETA)</code>) is proposed on the logit scale rather than on its packed <span class="math inline">\(\log\theta\)</span> scale, whose proposal has no ceiling at 1. The covariance is carried over by the delta method, and each importance weight includes the Jacobian <span class="math inline">\(|dx / d\operatorname{logit}\theta|\)</span> of its packed coordinate <span class="math inline">\(x\)</span>: <span class="math inline">\(1 - \theta\)</span> for the usual <span class="math inline">\(x = \log\theta\)</span>, <span class="math inline">\(\theta(1 - \theta)\)</span> when a negative lower bound packs it as <span class="math inline">\(x = \theta\)</span>. Only the proposal changes; the target is still the likelihood over the packed parameter box, now without the region <span class="math inline">\(\theta \ge 1\)</span> where <code>logit</code> is clamped (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1548">#1548</a>).</p>
<p>“The likelihood” needs a scale to be flat on. By default that is the packed scale: log-sd for a variance, <span class="math inline">\(\log\theta\)</span> for a positive θ. <code>sir_scale = natural</code> makes it the reported scale instead; see <a href="#choosing-the-target-scale">Choosing the target scale</a>.</p>
</section>
<section id="enabling-sir" class="level2">
<h2 class="anchored" data-anchor-id="enabling-sir">Enabling SIR</h2>
<p>Add <code>sir = true</code> to the <code>[fit_options]</code> block. The covariance step must also be enabled (it provides the proposal distribution):</p>
<pre><code>[fit_options]
  method     = focei
  covariance = true
  sir        = true</code></pre>
</section>
<section id="options" class="level2">
<h2 class="anchored" data-anchor-id="options">Options</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Key</th>
<th>Default</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sir</code></td>
<td><code>false</code></td>
<td>Enable/disable SIR</td>
</tr>
<tr class="even">
<td><code>sir_samples</code></td>
<td><code>1000</code></td>
<td>Number of proposal samples (M). Higher values give more reliable weights but take longer</td>
</tr>
<tr class="odd">
<td><code>sir_resamples</code></td>
<td><code>250</code></td>
<td>Number of resampled vectors (m). Must be less than <code>sir_samples</code></td>
</tr>
<tr class="even">
<td><code>sir_seed</code></td>
<td><code>12345</code></td>
<td>RNG seed for reproducibility</td>
</tr>
<tr class="odd">
<td><code>sir_keep_samples</code></td>
<td><code>false</code></td>
<td>Retain the resampled parameter vectors on <code>FitResult.sir_resamples_packed</code>. Required for <code>simulate_with_uncertainty()</code> with <code>UncertaintyMethod::Sir</code>. Adds <code>n_resamples × n_packed × 8</code> bytes to the result</td>
</tr>
<tr class="even">
<td><code>sir_df</code></td>
<td><code>5.0</code></td>
<td>Degrees of freedom ν for the Student-t proposal. Heavier tails (small ν) improve ESS for parameters near boundaries such as omega variances. Set to a large value (e.g.&nbsp;100) for near-normal behaviour. Dosne (2017) recommends ν=5.</td>
</tr>
<tr class="odd">
<td><code>sir_scale</code></td>
<td><code>packed</code></td>
<td>The scale the target is flat on: <code>packed</code> (log-sd for variances) or <code>natural</code> (variances, the PsN convention). See <a href="#choosing-the-target-scale">Choosing the target scale</a></td>
</tr>
</tbody>
</table>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">Output</h2>
<p>SIR adds the following to the estimation output:</p>
<ul>
<li><strong>95% CI</strong> for each theta, omega, and sigma parameter, and for each IOV kappa variance (2.5th and 97.5th percentiles; omega and kappa: the diagonal variances). The fit YAML’s <code>sir:</code> block is laid out in <a href="../output.html#sir-intervals-sir">Output Files</a></li>
<li><strong>Effective sample size (ESS)</strong>: a diagnostic indicating how well the proposal distribution matches the true uncertainty. ESS close to M indicates a good match; ESS much less than m suggests the proposal is a poor fit</li>
</ul>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<p>The effective sample size (ESS) is the primary diagnostic:</p>
<ul>
<li><strong>ESS &gt; m</strong> (resamples): excellent — the proposal distribution is well-matched</li>
<li><strong>ESS between 100 and m</strong>: adequate for most purposes</li>
<li><strong>ESS &lt; 100</strong>: the proposal may be a poor fit; consider a different estimation method or increasing <code>sir_samples</code>. SIR warns below this threshold; see <a href="#when-the-ess-is-below-100">When the ESS is below 100</a></li>
</ul>
<p>A well-behaved proposal has an ESS that <strong>scales linearly with <code>sir_samples</code></strong> at a roughly constant efficiency, and <strong>confidence intervals that are stable as <code>sir_samples</code> grows</strong>. Degenerate SIR shows the opposite: ESS plateaus or collapses toward a handful of dominant weights, and CIs jump between runs.</p>
<section id="benchmark-warfarin-bundled-datawarfarin.csv-10-subjects" class="level3">
<h3 class="anchored" data-anchor-id="benchmark-warfarin-bundled-datawarfarin.csv-10-subjects">Benchmark: warfarin (bundled <code>data/warfarin.csv</code>, 10 subjects)</h3>
<p>FOCE fit (<code>method = foce</code>, no interaction), proposal = ML covariance matrix, default Student-t (ν=5), <code>sir_resamples = 250</code>, <code>sir_seed = 1705</code>. ESS grows with the draw count at ~42–50% efficiency, and the theta CIs barely move with it — the signature of a healthy proposal:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><code>sir_samples</code></th>
<th>ESS</th>
<th>efficiency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1000</td>
<td>497</td>
<td>50%</td>
</tr>
<tr class="even">
<td>2000</td>
<td>833</td>
<td>42%</td>
</tr>
<tr class="odd">
<td>4000</td>
<td>1729</td>
<td>43%</td>
</tr>
</tbody>
</table>
<p>95% CIs (2000-sample run) bracket the point estimates:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Param</th>
<th>Estimate</th>
<th>SIR 95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TVCL</td>
<td>0.133</td>
<td>[0.121, 0.146]</td>
</tr>
<tr class="even">
<td>TVV</td>
<td>7.73</td>
<td>[7.16, 8.20]</td>
</tr>
<tr class="odd">
<td>TVKA</td>
<td>0.725</td>
<td>[0.517, 0.996]</td>
</tr>
<tr class="even">
<td>PROP_ERR</td>
<td>0.0107</td>
<td>[0.0093, 0.0134]</td>
</tr>
</tbody>
</table>
<p>Measured on Linux aarch64 (#1710). Earlier versions of this table (ESS 310 / 587 / 1097) were taken while a model-file <code>method = foce</code> still weighted SIR’s draws with the <strong>FOCEI</strong> objective, a different marginal from the one the proposal was centred on. With the same seed, those weights gave ESS 238 at 1000 draws here, and 4.9 of 1000 on warfarin_iov.</p>
<p>Re-measured after #1722 (FOCE EBEs with the residual variance held at <span class="math inline">\(f(\eta{=}0)\)</span>; macOS arm64): ESS 497 / 833 / 1730 and the 2000-sample θ CIs to the printed digits; the PROP_ERR upper limit reads 0.0136. Warfarin’s σ ≈ 1% puts the two EBE conventions close, so the benchmark barely moves. The FOCE fit + covariance + SIR (2000 draws) runs in ~0.3 s (macOS arm64, release); the covariance step is now the FD stencil, ~0.1 s before #1722.</p>
</section>
<section id="rank-deficient-and-non-identified-proposals" class="level3">
<h3 class="anchored" data-anchor-id="rank-deficient-and-non-identified-proposals">Rank-deficient and non-identified proposals</h3>
<p>The proposal is the fit’s asymptotic covariance matrix, and that matrix is often degenerate in ways SIR has to handle explicitly.</p>
<p><strong><code>FIX</code>ed parameters are never sampled.</strong> A fixed parameter has no uncertainty: its row/column in the covariance matrix is exactly zero and its packed bounds are pinned (<code>lower == upper</code>). SIR restricts the proposal to the <em>free</em> block, holds fixed parameters at their fixed values, and uses the free dimension as the Student-t dimensionality, so the importance weights stay consistent. This matters for model-based meta-analysis, where fixing the residual variance (<code>sigma ADD_ERR ~ 1.0 (variance) FIX</code>) <em>is</em> the inverse-variance weighting scheme and cannot be dropped.</p>
<p><strong>Directions the data do not identify are floored or shrunk, and reported.</strong> Two things can go wrong with the free block itself:</p>
<ul>
<li><p>A <strong>likelihood ridge</strong> — two parameters that determine only their sum — leaves a direction with (near-)zero variance. SIR floors it so the proposal stays positive definite, and warns that those parameter combinations are held at their ML values rather than explored.</p></li>
<li><p>A <strong>non-identified direction</strong> comes back from the covariance step with an enormous variance: the covariance Hessian’s near-zero eigenvalues are floored before inversion, so the inverse carries variances around <code>1 / floor</code> — thousands of standard deviations in packed (log) space. Drawing from that proposal unshrunk places every single sample outside the parameter bounds. SIR now caps each direction so ±2 proposal standard deviations still fit between the ML estimate and the <em>nearer</em> of its packed bounds, and warns that CIs along those directions understate the uncertainty. The room is measured from the estimate, not from the middle of the box: a <code>theta (0, 100)</code> estimated at <code>0.5</code> has far more room below it than above, and a cap derived from the box width would let most draws overshoot the upper bound. The Student-t tails are accounted for too, so the ±2 sd is a statement about the draws rather than about the scale matrix.</p>
<p>The cap is deliberately loose — it bites only a direction more than ten times wider than the room its parameters have — so a legitimately wide uncertainty is left alone. That gate matters most for the variance components, whose packed bounds are narrow (an omega log-Cholesky diagonal lives in <code>[-6, 6]</code>): a collapsing omega genuinely has log-scale uncertainty of that order, and shrinking it would silently narrow its CI and mislabel it as non-identified. The failure the cap exists for overshoots by a factor of 1e3–1e4.</p></li>
</ul>
<p>Both notes arrive as fit warnings prefixed <code>SIR:</code> and name the parameters involved, e.g.</p>
<pre><code>SIR: proposal was shrunk in 3 direction(s) so draws mostly stay inside the
parameter bounds [TVKA -0.74, ETA_KA -0.60, ETA_V +0.28 (sd 6.15e3 → 2.89e0); ETA_V +0.84,
TVV +0.36, ETA_CL +0.24 (sd 6.15e3 → 3.58e0); ...]. Those directions come from
eigenvalue-floored (non-identified) curvature in the covariance step; the SIR
CIs along them understate the true uncertainty.</code></pre>
<p>That example is the bundled warfarin model refitted with <code>PROP_ERR</code> fixed far from its ML value: the fit is misspecified, three of six free-block Hessian eigenvalues get floored, and before this the run died with <code>All SIR samples had invalid weights</code>. It now completes with an ESS of ~1 — which, together with the warning, is the honest answer: the proposal carries no usable information in those directions.</p>
<p>They are a signal about the <em>model</em>, not only about SIR: a direction the covariance step had to floor is a direction the data do not inform.</p>
<p><strong>When every sample is still rejected</strong>, the error names the failing check rather than just saying the weights were invalid — how many samples fell out of bounds, which coordinates’ bounds they hit, and what the proposal’s rank deficiency looks like:</p>
<pre><code>All 1000 SIR samples had invalid weights (rejected: 1000 out of bounds, 0
non-finite theta or non-positive sigma/omega/kappa variance, 0 non-finite OFV,
0 cancelled). Bound first overshot by: TVET50 (734), TVEMAX (266) (count of
samples, first offending coordinate only). Proposal covariance is rank-deficient
beyond the FIX-ed parameters: ...</code></pre>
<p>A theta is checked against its declared bounds and nothing else. A theta declared <code>(0, -50, 50)</code>, such as a level block, a covariate slope or a shift, is sampled on its natural scale and may go negative. A theta whose lower bound is 0 or more is sampled as <span class="math inline">\(\log\theta\)</span>, so it stays positive anyway. Only the variances (sigma and the omega and kappa diagonals) must be positive (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1701">#1701</a>).</p>
<p>The fit-time counterpart of this diagnosis is the covariance step’s own <code>Covariance step regularized: eigenvalue floor applied to FD Hessian ...</code> warning, which fires whenever the free-block Hessian had eigenvalues clipped.</p>
</section>
<section id="when-the-ess-is-below-100" class="level3">
<h3 class="anchored" data-anchor-id="when-the-ess-is-below-100">When the ESS is below 100</h3>
<p>Below an ESS of 100 the intervals rest on a few draws, and SIR says so with a <code>SIR:</code> warning rather than returning them silently (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1723">#1723</a>). The warning names the draw the intervals hinge on: its share of the weight, the coordinate it moves furthest (in proposal standard deviations), and that coordinate’s value on the reported scale.</p>
<p>Under the default <code>sir_scale = packed</code> it then checks each free Ω and κ variance. Each one is moved alone to its lower bound in the parameter box, with the EBEs re-solved, and the OFV is compared with the OFV recomputed at the estimates. For an η inside a <code>block_omega</code> or block κ, its covariances with the earlier ηs of the block are set to 0 as well, so its variance itself reaches the floor rather than only its correlation reaching ±1. A rise below χ²₁(0.95) = 3.84 means zero is inside that variance’s likelihood-ratio interval: the conditional ΔOFV is an upper bound on the profile ΔOFV. That variance’s SIR lower limit then reflects the parameter box rather than the data, and the warning names it. The check costs one inner loop per variance, plus one at the estimates, and runs only on a low-ESS run. It does not run the other way: a rise above 3.84 does not prove the variance is bounded away from zero, and the warning does not say it is.</p>
<p><code>warfarin_iov</code> fitted with FOCEI is the bundled example:</p>
<pre><code>SIR: effective sample size is 3.5 of 1000 draws, below the 100 at which the
proposal is adequate, so these intervals rest on few draws. The heaviest draw
carries 52.9% of the weight; it moves ETA_CL by -6.36 proposal standard
deviations from the proposal centre, to 4.585e-4 on the reported scale. Increase
`sir_samples` for more stable intervals. The data do not bound ETA_KA (ΔOFV 1.56
at variance 6.14e-6) away from zero: each, moved to its lower bound in the
parameter box with the other parameters at the estimates, costs less than
χ²₁(0.95) = 3.84 in OFV, so its SIR lower limit reflects the parameter box rather
than the data. `sir_scale = natural` makes these lower limits independent of the
box.</code></pre>
<p>A flagged η inside a block whose covariances the check set to 0 carries “, with its covariances in the block also set to 0” after its variance.</p>
<p>With fewer than 100 draws the ESS cannot reach 100 at all, so the first sentence says that instead.</p>
<section id="variances-the-data-do-not-bound-away-from-zero" class="level4">
<h4 class="anchored" data-anchor-id="variances-the-data-do-not-bound-away-from-zero">Variances the data do not bound away from zero</h4>
<p>The proposal is not at fault on that fit. An independent finite-difference Hessian reproduces the covariance step to about four digits. The <em>target</em> is flat. ΔOFV with one packed log-sd moved toward the floor, the others at their estimates (Linux aarch64; identical on macOS arm64):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>coordinate</th>
<th>Δ = −1</th>
<th>−2</th>
<th>−3</th>
<th>−5</th>
<th>at the floor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ETA_CL</td>
<td>5.15</td>
<td>8.58</td>
<td>9.21</td>
<td>9.31</td>
<td>9.31</td>
</tr>
<tr class="even">
<td>ETA_V</td>
<td>8.41</td>
<td>16.11</td>
<td>17.80</td>
<td>18.08</td>
<td>18.09</td>
</tr>
<tr class="odd">
<td><strong>ETA_KA</strong></td>
<td><strong>1.05</strong></td>
<td><strong>1.48</strong></td>
<td><strong>1.55</strong></td>
<td><strong>1.56</strong></td>
<td><strong>1.56</strong></td>
</tr>
<tr class="even">
<td>KAPPA_CL</td>
<td>23.15</td>
<td>64.82</td>
<td>75.02</td>
<td>76.75</td>
<td>76.78</td>
</tr>
</tbody>
</table>
<p>ETA_KA’s likelihood is a shelf that runs down to the floor at ω² = e⁻¹² ≈ 6e-6. No proposal centred on the estimate covers it, so a few far-tail draws carry the weight. ESS grows super-linearly with the draw count: 3.5, 8.3, 22.3 and 214 at 1000, 2000, 4000 and 40 000 draws. Under the packed target the ω²_KA lower limit follows the floor: 4.9e-4, 1.2e-4 and 1.0e-4 with the floor at −4, −6 and −9. A 500-replicate bootstrap puts ω²_KA below 1e-4 in 30% of replicates.</p>
<p>What to do: do not read that SIR lower limit as a property of the data. Profile the variance, bootstrap, or use <code>sir_scale = natural</code>.</p>
</section>
</section>
<section id="choosing-the-target-scale" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-target-scale">Choosing the target scale</h3>
<p>SIR’s target is the likelihood times a flat prior, and the two scales differ only where the likelihood is flat, which is where a variance’s interval comes from.</p>
<ul>
<li><strong><code>packed</code></strong> (default): flat in log-sd (<code>ln L_kk</code>) for an Ω / κ / σ, in <span class="math inline">\(\log\theta\)</span> for a positive θ, and in θ for one whose lower bound is negative. A variance the data do not bound away from zero has a shelf down to the box floor, as above.</li>
<li><strong><code>natural</code></strong>: flat on the reported scale. That is Ω and κ variances and covariances (<code>vech Σ</code>), σ as a <strong>variance</strong> whatever its declaration (NONMEM’s natural σ), θ as declared, and a <code>block_sigma</code> ρ as a correlation. This is the PsN convention. Each draw’s weight gains <span class="math inline">\(\log\lvert\partial n / \partial x\rvert\)</span>, and the proposal is re-centred on the tilted target’s Laplace mode, <span class="math inline">\(\hat x + C\,\nabla\log\lvert J\rvert\)</span>, clamped into the box. The proposal’s shape is unchanged.</li>
</ul>
<p>Neither is right everywhere. The natural target has a heavy <em>upper</em> tail wherever a variance is informed by few groups, such as a between-study variance over six studies. ESS, <code>sir_resamples = 250</code>, seed 1705, ν = 5 (Linux aarch64; identical on macOS arm64):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>fixture</th>
<th>target</th>
<th>1000 draws</th>
<th>4000 draws</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>warfarin_iov</code>, FOCEI</td>
<td>packed</td>
<td>3.5</td>
<td>22.3</td>
</tr>
<tr class="even">
<td></td>
<td>natural</td>
<td>139.8</td>
<td>813.7</td>
</tr>
<tr class="odd">
<td><code>mbma_placebo</code> (6 studies, BTAV κ)</td>
<td>packed</td>
<td>143.2</td>
<td>820.6</td>
</tr>
<tr class="even">
<td></td>
<td>natural</td>
<td>35.2</td>
<td>252.6</td>
</tr>
</tbody>
</table>
<p><code>natural</code> is refused for a model with a <code>prior(...)</code>: a declared prior is a density on the packed scale, so the target is already the likelihood times that prior, and there is no flat prior to move to the reported scale.</p>
<p><code>packed</code> stays the default because the MBMA shape is the one ferx is built for. Under <code>natural</code>, a low-ESS warning points back to <code>packed</code> instead of probing the floors: the natural target’s lower limits do not depend on the box. With the ω / κ floors moved from −4 to −9 at 40 000 draws, the ω²_KA lower limit moves 5.05e-4 → 1.01e-4 under <code>packed</code> and 5.04e-3 → 5.30e-3 under <code>natural</code>. Under <code>natural</code> that difference is Monte Carlo noise.</p>
<p>There is no external reference for the natural intervals here (PsN is not available). They are validated by the exact Jacobian (checked against a finite-difference determinant), by the box independence above, and by agreement with the un-re-centred natural target at 40 000 draws: re-centring changes efficiency, not the target.</p>
</section>
</section>
<section id="computational-cost" class="level2">
<h2 class="anchored" data-anchor-id="computational-cost">Computational Cost</h2>
<p>SIR evaluates the inner loop (EBE optimization) for each of the M proposal samples. With the default M=1000, this is roughly 3-10x the cost of the estimation step itself. The computation is parallelized across samples and warm-started from the ML EBEs to minimize runtime.</p>
<p>The resampling step itself is negligible.</p>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<pre><code>[fit_options]
  method        = focei
  covariance    = true
  sir           = true
  sir_samples   = 1000
  sir_resamples = 250
  sir_seed      = 42</code></pre>
</section>
<section id="running-sir-after-a-fit-run_sir" class="level2">
<h2 class="anchored" data-anchor-id="running-sir-after-a-fit-run_sir">Running SIR after a fit (<code>run_sir</code>)</h2>
<p>SIR can also be run as a standalone step against a <code>FitResult</code> that was produced earlier — useful when the original fit was expensive and you want to add SIR without re-estimating, or when working with a fit loaded from a <code>.fitrx</code> bundle.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="pp">ferx_core::</span><span class="op">{</span>fit_from_files<span class="op">,</span> run_sir<span class="op">,</span> FitOptions<span class="op">};</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> <span class="kw">mut</span> opts <span class="op">=</span> <span class="pp">FitOptions::</span><span class="kw">default</span>()<span class="op">;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>opts<span class="op">.</span>run_covariance_step <span class="op">=</span> <span class="cn">true</span><span class="op">;</span>          <span class="co">// SIR needs the cov matrix</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> fit <span class="op">=</span> fit_from_files(<span class="st">"model.ferx"</span><span class="op">,</span> <span class="cn">Some</span>(<span class="st">"data.csv"</span>)<span class="op">,</span> <span class="cn">None</span><span class="op">,</span> <span class="cn">Some</span>(opts<span class="op">.</span>clone()))<span class="op">?;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>opts<span class="op">.</span>sir_samples   <span class="op">=</span> <span class="dv">2000</span><span class="op">;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>opts<span class="op">.</span>sir_resamples <span class="op">=</span> <span class="dv">500</span><span class="op">;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> fit_with_sir <span class="op">=</span> run_sir(<span class="op">&amp;</span>fit<span class="op">,</span> <span class="cn">None</span><span class="op">,</span> <span class="cn">None</span><span class="op">,</span> <span class="op">&amp;</span>opts)<span class="op">?;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>run_sir</code> re-uses the fit’s covariance matrix as the SIR proposal and the per-subject EBEs from <code>fit.subjects</code> to warm-start the inner loop. The returned <code>FitResult</code> is a clone of <code>fit</code> with <code>sir_ci_theta</code>, <code>sir_ci_omega</code>, <code>sir_ci_sigma</code>, <code>sir_ci_kappa</code> (IOV models), <code>sir_ess</code>, <code>sir_seed</code>, <code>sir_settings</code> and (when <code>sir_keep_samples = true</code>) <code>sir_resamples_packed</code> replaced by this run’s.</p>
<section id="which-settings-run_sir-uses" class="level3">
<h3 class="anchored" data-anchor-id="which-settings-run_sir-uses">Which settings <code>run_sir</code> uses</h3>
<p>A fit that ran SIR records every setting its draws were scored under in <code>FitResult::sir_settings</code> (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1758">#1758</a>): <code>samples</code>, <code>resamples</code>, the <code>seed</code> actually used (the built-in default when <code>sir_seed</code> was unset), <code>df</code>, <code>scale</code>, <code>keep_samples</code>, and in <code>sir_settings.scoring</code> the inner-loop settings (<code>inner_maxiter</code>, <code>inner_tol</code>, <code>inner_restarts</code>, <code>mu_referencing</code>, <code>n_agq</code>, <code>inner_optimizer</code>, <code>ebe_warm_start</code>) and the six <code>ode_*</code> solver settings. That scoring half is the same record every fit carries in <code>FitResult::scoring_settings</code> (<a href="https://github.com/FeRx-NLME/ferx-core/issues/426">#426</a>), here as the draws ran it; <code>inner_restarts</code> is recorded but unused, since the draws are warm-started. <code>FitResult::sir_seed</code> is the same resolved seed; both are <code>None</code> exactly when SIR did not run. On a fit saved before #1758 there is no record and <code>sir_seed</code> is the seed the fit was <em>given</em> (so <code>None</code> for a SIR on the default seed).</p>
<p><code>run_sir</code> takes each of these from the record <strong>wherever the caller’s <code>FitOptions</code> holds the default value</strong>, and the caller’s value otherwise. So <code>run_sir(&amp;fit, …, &amp;FitOptions::default())</code> repeats the fit’s own SIR, bit for bit (ESS and every interval), and passing only <code>sir_samples = 2000</code> changes the draw count and keeps the fit’s scale, degrees of freedom and seed. The recorded ODE solver settings reach every draw’s integration, and the recorded <code>inner_optimizer</code> / <code>ebe_warm_start</code> are the ones the draws re-solve with, so a later fit in the same process cannot change which inner solver they use. A fit with no SIR record (SIR never ran, or a <code>.fitrx</code> saved before #1758) uses the caller’s options as given, except that an unset <code>sir_seed</code> takes the fit’s <code>sir_seed</code>. <code>run_sir</code> does not read <code>FitResult::scoring_settings</code>: the in-fit SIR scores with the fit’s top-level options rather than the producing stage’s, and on a Laplace fit the two differ in <code>inner_tol</code>. <code>inner_optimizer</code> / <code>ebe_warm_start</code> apply to this call’s draws only, and nothing they set outlives the call (<a href="https://github.com/FeRx-NLME/ferx-core/issues/426">#426</a>).</p>
<p>The test is by value, so <strong>an explicit default cannot override a non-default record</strong>: <code>sir_scale = SirScale::Packed</code> on a fit recorded <code>natural</code> reruns <code>natural</code>. To force a default, write it into <code>fit.sir_settings</code> (or set that field to <code>None</code>) before calling. <code>method</code> and <code>interaction</code> are not part of the record; the scored marginal comes from the fit itself (#1710).</p>
<p>After a <code>.fitrx</code> round trip the record is intact, but the bundle stores EBEs at 6 decimals (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1631">#1631</a>) and they warm-start every draw, so the repeat is close rather than bit-identical: on the bundled warfarin example the ESS moved by 8.5e-11 relative (measured on macOS arm64).</p>
</section>
<section id="which-objective-weights-the-draws" class="level3">
<h3 class="anchored" data-anchor-id="which-objective-weights-the-draws">Which objective weights the draws</h3>
<p>Every draw is weighted with the objective the fit minimised, so <code>run_sir(&amp;fit, None, None, &amp;opts)</code> reproduces the SIR that <code>fit()</code> runs with <code>sir = true</code> at the same <code>sir_samples</code>, <code>sir_resamples</code> and <code>sir_seed</code>, bit for bit (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1755">#1755</a>):</p>
<ul>
<li><strong>The fit’s method, not the caller’s.</strong> <code>method</code> and <code>interaction</code> come from the fit (<code>fit.method</code>, the last estimating stage of a chain), whatever <code>opts</code> says. A Laplace fit is scored with the Laplace marginal even when <code>opts</code> is <code>FitOptions::default()</code> (FOCEI). The same holds inside <code>fit()</code>: a chain <code>methods = [focei, laplace]</code> scores its SIR with Laplace, the stage that produced the estimates. <code>run_covariance</code> takes the method from the fit in the same way.</li>
<li><strong>The mixture marginal for a <code>[mixture]</code> model.</strong> Each draw is scored with the K-class marginal the mixture fit reports as its OFV, and the per-class Ω/Σ overrides (<code>omega(2) ETA_CL ~ …</code>) are rebuilt from the fit (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1704">#1704</a>). The SIR intervals cover the base θ/Ω/Σ; the overrides are sampled but get no interval of their own.</li>
</ul>
<p>Two limits:</p>
<ul>
<li><strong><code>n_agq</code> comes from the fit’s SIR record.</strong> A fit that ran SIR records its AGQ node count in <code>sir_settings</code> (see <a href="#which-settings-run_sir-uses">Which settings <code>run_sir</code> uses</a>); for a fit with no record (no SIR ran, or a <code>.fitrx</code> saved before <a href="https://github.com/FeRx-NLME/ferx-core/issues/1758">#1758</a>) and <code>n_agq &gt; 1</code>, pass the same <code>n_agq</code> the fit used.</li>
<li><strong>Mixture overrides are not stored on a <code>FitResult</code>.</strong> Their fitted values are carried only by the in-memory result of a FOCE, FOCEI, Laplace or Gauss-Newton <code>fit()</code>. For a <code>[mixture]</code> model with at least one override, <code>run_sir</code> and <code>run_covariance</code> return an error on a fit loaded from <code>.fitrx</code>, built in R, or estimated by SAEM, IMP or Bayes (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1765">#1765</a>). A mixture model without overrides is not affected.</li>
</ul>
</section>
<section id="caller-supplied-vs.-re-read-inputs" class="level3">
<h3 class="anchored" data-anchor-id="caller-supplied-vs.-re-read-inputs">Caller-supplied vs.&nbsp;re-read inputs</h3>
<p>The second and third arguments to <code>run_sir</code> are <code>Option&lt;&amp;CompiledModel&gt;</code> and <code>Option&lt;&amp;Population&gt;</code>:</p>
<ul>
<li><strong>Supplied (<code>Some(...)</code>)</strong>: not hash-checked — the in-memory value carries no source bytes — but it must be the fitted one (below). A supplied model with <code>population = None</code> re-reads the data with the fit’s recorded reader settings, without opening the model file. On a fit that records none (a <code>.fitrx</code> saved before <a href="https://github.com/FeRx-NLME/ferx-core/issues/1685">#1685</a>) it reads the model file instead, hash-verified, for its <code>[data]</code> renames and <code>[data_selection]</code>; pass both to avoid reading it.</li>
<li><strong><code>None</code></strong>: <code>run_sir</code> re-reads from <code>fit.model_path</code> / <code>fit.data_path</code> (set automatically by <code>fit_from_files</code>). If <code>fit.model_hash</code> / <code>fit.data_hash</code> is set, the file is hashed and compared against the stored digest. <strong>A mismatch is a hard error</strong> — the whole point of <code>run_sir</code> is to refuse SIR against stale source.</li>
</ul>
<p>The re-read reads the data the way the fit did, <code>[data_selection]</code> included, and binds the model from the fit’s <code>data_bindings</code>: the fit’s level layout and its <code>[covariate_model]</code> statistics, never the ones the data at hand would give. A fit whose bindings are empty (a <code>.fitrx</code> saved before they were recorded) is refused when the model has a level block or a symbolic covariate centre; refit it. A supplied model must carry the fit’s bindings and θ count, and the population must hold the fit’s subjects in the fit’s order. Each is refused otherwise rather than evaluated at the wrong θ layout (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1622">#1622</a>). When the fit records no bindings, a supplied model’s covariate statistics are instead checked against the population being scored (supplied or re-read), and must match exactly: the model bound on the fit’s own data passes, and one bound on a simulation design is refused (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1729">#1729</a>). Re-parse it and bind it on the fit’s data (<code>prepare_run</code> on the fit’s files); calling <code>bind_covariate_stats</code> again on an already-bound model changes nothing. <code>run_covariance</code> resolves its inputs the same way.</p>
<p>This means <code>run_sir(&amp;fit, None, None, &amp;opts)</code> “just works” after <code>fit_from_files</code>, with built-in integrity checking. For in-memory workflows where <code>fit()</code> was called directly (no paths recorded), pass the model and population explicitly.</p>
</section>
<section id="the-population-the-fit-was-given" class="level3">
<h3 class="anchored" data-anchor-id="the-population-the-fit-was-given">The population the fit was given</h3>
<p>A fit records how it read its data and what it was given (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1685">#1685</a>):</p>
<ul>
<li><strong><code>reader_settings</code></strong>: the <code>[data]</code> renames, <code>[covariates]</code>, <code>iov_column</code> and <code>[data_selection]</code> clauses the file entry points (<code>fit_from_files</code>, <code>prepare_run</code>, the CLI) read with, including any row filter the caller added on top of the model file’s (<code>FitOptions::ignore_exprs</code> passed to <code>fit_from_files</code>). The re-read replays them. Before #1685 it took the model file’s settings, so such a filter was silently dropped and the step ran on rows the fit never saw.</li>
<li><strong><code>iov_occasion</code></strong>: the occasion rule the fit ran under (<a href="https://github.com/FeRx-NLME/ferx-core/issues/1783">#1783</a>). <code>run_sir</code> and <code>run_covariance</code> prepare the population as <code>fit()</code> did: occasions derived with this rule, and DV log-transformed for a <code>log(DV) ~ ...</code> model. So <code>population = None</code> and the population <code>prepare_run</code> reads give the same result as the one <code>run_model_with_data</code> returns. The caller’s <code>options.iov_occasion</code> is not read, just as <code>method</code> is not. A <code>.fitrx</code> saved before #1783 records no rule: the steps use the model file’s rule when they read the file, and a warning on the result names it. That guess is wrong for a <code>fit_from_files</code> fit whose caller passed another rule, since <code>fit_from_files</code> ignores the file’s <code>[fit_options]</code>. Set <code>fit.iov_occasion</code> to the rule the fit ran with. If the population then carries no occasion labels on an IOV model, the call is refused; pass the population <code>run_model_with_data</code> returned.</li>
<li><strong><code>population_fingerprint</code></strong>: a per-subject digest of every record, dose and covariate value of the population <code>fit()</code> was given. <code>run_sir</code> and <code>run_covariance</code> refuse any population, supplied or re-read, that does not match it, and name the first subject that differs and how: its observation records, its doses (a dose-row filter such as <code>ignore = EVID == 1 &amp;&amp; TIME &gt; 0</code> changes no observation), its covariate values, or the covariate columns. A population never bound for the model’s <code>theta NAME[...]</code> block hears which binder to call. Without the check, each of these ran and returned numbers: a flat Hessian, an SIR effective sample size of 298 of 300, a standard error 7,800 times the fitted one.</li>
</ul>
<p>With recorded settings, an IOV model passed as <code>Some(model)</code> with <code>population = None</code> runs too, since the fit records its <code>iov_column</code>. A fit without either record — a <code>.fitrx</code> saved before #1685 — is resolved as before, without the check. A fingerprint written by a ferx version with another encoding scheme is not compared: the recorded settings are still replayed, the population is not verified, and the result carries a warning saying so.</p>
</section>
<section id="hash-storage-on-fitresult" class="level3">
<h3 class="anchored" data-anchor-id="hash-storage-on-fitresult">Hash storage on <code>FitResult</code></h3>
<p>When you go through <code>fit_from_files</code> or <code>run_model_with_data</code>, the resulting <code>FitResult</code> carries:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>model_path: Option&lt;String&gt;</code></td>
<td>The <code>.ferx</code> path as supplied (no canonicalisation)</td>
</tr>
<tr class="even">
<td><code>data_path:  Option&lt;String&gt;</code></td>
<td>The data CSV path as supplied</td>
</tr>
<tr class="odd">
<td><code>model_hash: Option&lt;String&gt;</code></td>
<td>SHA-256 hex digest of the model file at fit time</td>
</tr>
<tr class="even">
<td><code>data_hash:  Option&lt;String&gt;</code></td>
<td>SHA-256 hex digest of the data file at fit time</td>
</tr>
<tr class="odd">
<td><code>reader_settings: Option&lt;ReaderSettings&gt;</code></td>
<td>The settings the data were read with (see above)</td>
</tr>
<tr class="even">
<td><code>population_fingerprint: Option&lt;PopulationFingerprint&gt;</code></td>
<td>Set by every <code>fit()</code>, including in-memory ones</td>
</tr>
<tr class="odd">
<td><code>iov_occasion: Option&lt;IovOccasionRule&gt;</code></td>
<td>The occasion rule the fit ran under; set by every <code>fit()</code></td>
</tr>
</tbody>
</table>
<p>These fields round-trip through <code>.fitrx</code> save/load, so a loaded fit can still be SIR’d against the original files (provided they’re still on disk and unchanged).</p>
</section>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<p>Dosne A-G, Bergstrand M, Karlsson MO. “Improving the estimation of parameter uncertainty distributions in nonlinear mixed effects models using sampling importance resampling.” <em>J Pharmacokinet Pharmacodyn</em>. 2017;44(6):539-562. doi:10.1007/s10928-017-9542-0</p>


</section>
</section>

</main> <!-- /main -->
<script>
(function () {
  var HEAD = '<div class="panel-head"><span class="dots"><i></i><i></i><i></i></span><span class="file"><span class="br">[</span>warfarin_pk.ferx<span class="br">]</span></span></div>';

  function apply() {
    var dark = document.documentElement.getAttribute('data-bs-theme') === 'dark';
    document.querySelectorAll('div.sourceCode').forEach(function (el) {
      if (el.parentElement && el.parentElement.closest('.code-panel')) return;
      if (dark) {
        if (!el.classList.contains('code-panel')) {
          el.classList.add('code-panel');
          el.insertAdjacentHTML('afterbegin', HEAD);
        }
      } else {
        el.classList.remove('code-panel');
        var h = el.querySelector(':scope > .panel-head');
        if (h) h.remove();
      }
    });
  }

  if (document.body) apply();
  document.addEventListener('DOMContentLoaded', apply);
  new MutationObserver(function (ms) {
    ms.forEach(function (m) { if (m.attributeName === 'data-bs-theme') apply(); });
  }).observe(document.documentElement, { attributes: true });
}());
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ferx-nlme\.org\/ferx-core\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 FeRx-NLME · MIT licensed</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FeRx-NLME/ferx-core/edit/main/estimation/sir.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/FeRx-NLME/ferx-core/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Fe · 26 · Rx · 2026</p>
</div>
  </div>
</footer>




</body></html>